/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the plan_med_proc table.
 */
public class PlanMedProcPk implements Serializable
{
	protected Integer idplanmedproc;

	/** 
	 * Sets the value of idplanmedproc
	 */
	public void setIdplanmedproc(Integer idplanmedproc)
	{
		this.idplanmedproc = idplanmedproc;
	}

	/** 
	 * Gets the value of idplanmedproc
	 */
	public Integer getIdplanmedproc()
	{
		return idplanmedproc;
	}

	/**
	 * Method 'PlanMedProcPk'
	 * 
	 */
	public PlanMedProcPk()
	{
	}

	/**
	 * Method 'PlanMedProcPk'
	 * 
	 * @param idplanmedproc
	 */
	public PlanMedProcPk(final Integer idplanmedproc)
	{
		this.idplanmedproc = idplanmedproc;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PlanMedProcPk)) {
			return false;
		}
		
		final PlanMedProcPk _cast = (PlanMedProcPk) _other;
		if (idplanmedproc == null ? _cast.idplanmedproc != idplanmedproc : !idplanmedproc.equals( _cast.idplanmedproc )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idplanmedproc != null) {
			_hashCode = 29 * _hashCode + idplanmedproc.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.sorin.idea.dto.PlanMedProcPk: " );
		ret.append( "idplanmedproc=" + idplanmedproc );
		return ret.toString();
	}

}
