/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.jdbc;


import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.Date;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

import com.sorin.idea.dao.*;
import com.sorin.idea.dto.*;
import com.sorin.idea.exceptions.*;
import com.sorin.idea.factory.*;
import com.sorin.idea.util.UtilFechas;

public class ArrEstudioIntentoDaoImpl extends AbstractDAO implements ArrEstudioIntentoDao
{
	private AuditoriaDao auditoriaDao = new AuditoriaDao();
    private AuditoriaDto auditoriaDto = null;
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT IDESTUDIO, IDNIVEL1, IDNIVEL2, IDNIVEL3, OTROS FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( IDESTUDIO, IDNIVEL1, IDNIVEL2, IDNIVEL3, OTROS ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET IDESTUDIO = ?, IDNIVEL1 = ?, IDNIVEL2 = ?, IDNIVEL3 = ?, OTROS = ? WHERE IDESTUDIO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE IDESTUDIO = ?";

	/** 
	 * Index of column IDESTUDIO
	 */
	protected static final int COLUMN_IDESTUDIO = 1;

	/** 
	 * Index of column IDNIVEL1
	 */
	protected static final int COLUMN_IDNIVEL1 = 2;

	/** 
	 * Index of column IDNIVEL2
	 */
	protected static final int COLUMN_IDNIVEL2 = 3;

	/** 
	 * Index of column IDNIVEL3
	 */
	protected static final int COLUMN_IDNIVEL3 = 4;

	/** 
	 * Index of column OTROS
	 */
	protected static final int COLUMN_OTROS = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column IDESTUDIO
	 */
	protected static final int PK_COLUMN_IDESTUDIO = 1;

	/** 
	 * Inserts a new row in the ARR_ESTUDIO_INTENTO table.
	 */
	public ArrEstudioIntentoPk insert(ArrEstudioIntento dto) throws ArrEstudioIntentoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			if (dto.getIdestudio() != null) {
				stmt.setInt( index++, dto.getIdestudio().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdnivel1() != null) {
				stmt.setInt( index++, dto.getIdnivel1().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdnivel2() != null) {
				stmt.setInt( index++, dto.getIdnivel2().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdnivel3() != null) {
				stmt.setInt( index++, dto.getIdnivel3().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getOtros() );
			int rows = stmt.executeUpdate();auditoriaDto.setAccion(AuditoriaDto.insercion);
	        auditoriaDto.setDescri(dto.toString());
	        auditoriaDao.escribeAuditoria(auditoriaDto);
			long t2 = System.currentTimeMillis();
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			throw new ArrEstudioIntentoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the ARR_ESTUDIO_INTENTO table.
	 */
	public void update(ArrEstudioIntentoPk pk, ArrEstudioIntento dto) throws ArrEstudioIntentoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			if (dto.getIdestudio() != null) {
				stmt.setInt( index++, dto.getIdestudio().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdnivel1() != null) {
				stmt.setInt( index++, dto.getIdnivel1().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdnivel2() != null) {
				stmt.setInt( index++, dto.getIdnivel2().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdnivel3() != null) {
				stmt.setInt( index++, dto.getIdnivel3().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getOtros() );
			if (pk.getIdestudio() != null) {
				stmt.setInt( 6, pk.getIdestudio().intValue() );
			} else {
				stmt.setNull(6, java.sql.Types.INTEGER);
			}
		
			int rows = stmt.executeUpdate();
			auditoriaDto.setAccion(AuditoriaDto.modificacion);
	        auditoriaDto.setDescri(dto.toString());
	        auditoriaDao.escribeAuditoria(auditoriaDto);
			reset(dto);
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new ArrEstudioIntentoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the ARR_ESTUDIO_INTENTO table.
	 */
	public void delete(ArrEstudioIntentoPk pk) throws ArrEstudioIntentoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE );
			if (pk.getIdestudio() != null) {
				stmt.setInt( 1, pk.getIdestudio().intValue() );
			} else {
				stmt.setNull(1, java.sql.Types.INTEGER);
			}
		
			int rows = stmt.executeUpdate();
			auditoriaDto.setAccion(AuditoriaDto.borrado);
	        auditoriaDto.setDescri(pk.toString());
	        auditoriaDao.escribeAuditoria(auditoriaDto);
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new ArrEstudioIntentoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the ARR_ESTUDIO_INTENTO table that matches the specified primary-key value.
	 */
	public ArrEstudioIntento findByPrimaryKey(ArrEstudioIntentoPk pk) throws ArrEstudioIntentoDaoException
	{
		return findByPrimaryKey( pk.getIdestudio() );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_INTENTO table that match the criteria 'IDESTUDIO = :idestudio AND IDINTENTO = :idintento'.
	 */
	public ArrEstudioIntento findByPrimaryKey(Integer idestudio) throws ArrEstudioIntentoDaoException
	{
		ArrEstudioIntento ret[] = findByDynamicSelect( SQL_SELECT + " WHERE IDESTUDIO = ?", new Object[] { idestudio } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_INTENTO table that match the criteria ''.
	 */
	public ArrEstudioIntento[] findAll() throws ArrEstudioIntentoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY IDESTUDIO", null );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_INTENTO table that match the criteria 'IDESTUDIO = :idestudio'.
	 */
	public ArrEstudioIntento[] findWhereIdestudioEquals(long idestudio) throws ArrEstudioIntentoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDESTUDIO = ? ORDER BY IDESTUDIO DESC", new Object[] {  new Long(idestudio) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_INTENTO table that match the criteria 'IDNIVEL1 = :idnivel1'.
	 */
	public ArrEstudioIntento[] findWhereIdnivel1Equals(long idnivel1) throws ArrEstudioIntentoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDNIVEL1 = ? ORDER BY IDNIVEL1", new Object[] {  new Long(idnivel1) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_INTENTO table that match the criteria 'IDNIVEL2 = :idnivel2'.
	 */
	public ArrEstudioIntento[] findWhereIdnivel2Equals(long idnivel2) throws ArrEstudioIntentoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDNIVEL2 = ? ORDER BY IDNIVEL2", new Object[] {  new Long(idnivel2) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_INTENTO table that match the criteria 'IDNIVEL3 = :idnivel3'.
	 */
	public ArrEstudioIntento[] findWhereIdnivel3Equals(long idnivel3) throws ArrEstudioIntentoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDNIVEL3 = ? ORDER BY IDNIVEL3", new Object[] {  new Long(idnivel3) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_INTENTO table that match the criteria 'OTROS = :otros'.
	 */
	public ArrEstudioIntento[] findWhereOtrosEquals(String otros) throws ArrEstudioIntentoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE OTROS = ? ORDER BY OTROS", new Object[] { otros } );
	}

	/**
	 * Method 'ArrEstudioIntentoDaoImpl'
	 * 
	 */
	public ArrEstudioIntentoDaoImpl(String usuario)
	{
		this.auditoriaDto = new AuditoriaDto(usuario, getTableName());
	}
	public ArrEstudioIntentoDaoImpl(final java.sql.Connection userConn,String usuario)
	{
		this.userConn = userConn;
		this.auditoriaDto = new AuditoriaDto(usuario, getTableName());
	}

	/**
	 * Method 'ArrEstudioIntentoDaoImpl'
	 * 
	 * @param userConn
	 */
	public ArrEstudioIntentoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		//return "idea.ARR_ESTUDIO_INTENTO";
		return "idea.arr_estudio_intento";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ArrEstudioIntento fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ArrEstudioIntento dto = new ArrEstudioIntento();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ArrEstudioIntento[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ArrEstudioIntento dto = new ArrEstudioIntento();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ArrEstudioIntento ret[] = new ArrEstudioIntento[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}
	
	protected ArrEstudioIntento[] fetchMultiResultsStat(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ArrEstudioIntento dto = new ArrEstudioIntento();
			populateDtoStat( dto, rs);
			resultList.add( dto );
		}
		
		ArrEstudioIntento ret[] = new ArrEstudioIntento[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ArrEstudioIntento dto, ResultSet rs) throws SQLException
	{
		dto.setIdestudio( new Integer( rs.getInt(COLUMN_IDESTUDIO) ) );
		dto.setIdnivel1( new Integer( rs.getInt(COLUMN_IDNIVEL1) ) );
		if (rs.wasNull()) {
			dto.setIdnivel1( null );
		}
		
		dto.setIdnivel2( new Integer( rs.getInt(COLUMN_IDNIVEL2) ) );
		if (rs.wasNull()) {
			dto.setIdnivel2( null );
		}
		
		dto.setIdnivel3( new Integer( rs.getInt(COLUMN_IDNIVEL3) ) );
		if (rs.wasNull()) {
			dto.setIdnivel3( null );
		}
		
		dto.setOtros( rs.getString( COLUMN_OTROS ) );
	}
	
	protected void populateDtoStat(ArrEstudioIntento dto, ResultSet rs) throws SQLException
	{
		dto.setIdestudio( new Integer( rs.getInt(COLUMN_IDESTUDIO) ) );
		dto.setIdnivel1( new Integer( rs.getInt(COLUMN_IDNIVEL1) ) );
		if (rs.wasNull()) {
			dto.setIdnivel1( null );
		}
		
		dto.setIdnivel2( new Integer( rs.getInt(COLUMN_IDNIVEL2) ) );
		if (rs.wasNull()) {
			dto.setIdnivel2( null );
		}
		
		dto.setIdnivel3( new Integer( rs.getInt(COLUMN_IDNIVEL3) ) );
		if (rs.wasNull()) {
			dto.setIdnivel3( null );
		}
		
		dto.setOtros( rs.getString( COLUMN_OTROS ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ArrEstudioIntento dto)
	{
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_INTENTO table that match the specified arbitrary SQL statement
	 */
	public ArrEstudioIntento[] findByDynamicSelect(String sql, Object[] sqlParams) throws ArrEstudioIntentoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new ArrEstudioIntentoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}
	
	public ArrEstudioIntento[] findByDynamicSelect(String sql) throws ArrEstudioIntentoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResultsStat(rs);
		}
		catch (Exception _e) {
			throw new ArrEstudioIntentoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_INTENTO table that match the specified arbitrary SQL statement
	 */
	public ArrEstudioIntento[] findByDynamicWhere(String sql, Object[] sqlParams) throws ArrEstudioIntentoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new ArrEstudioIntentoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}
	
	/** 
	 * ESTADISTICAS
	 * @throws ArrEstudioIntentoDaoException 
	 */
	public ArrEstudioIntento[] getEstadisticas(ArrEstudioIntento intento) throws ArrEstudioIntentoDaoException
	{
		StringBuffer sql = new StringBuffer();
		sql.append("select pac.nhc paciente,");
		sql.append("i.idnivel1 TIPO,");
		sql.append("i.idnivel2 COMPLICACION,");
		sql.append("i.idnivel3 BLOQUEO,");
		sql.append("i.otros OTRA_COMP");
		sql.append(" from arr_estudio_intento i,");
		sql.append(" ARR_ESTUDIO e, ARR_PACIENTES pac");
		sql.append(" where i.idestudio = e.idestudio");
		sql.append(" and e.idpaciente = pac.codigo");
		sql.append(generaWhere(intento));
		sql.append(" order by 1");

		return findByDynamicSelect(sql.toString());
	}

	private String generaWhere(ArrEstudioIntento intento) {
		String where = "";
		//Filtro de intento
		if(intento != null && intento.getIdnivel1() != null && intento.getIdnivel1() > 0)
			where += " and i.idnivel1 = " + intento.getIdnivel1();
		return where;
	}

}
