/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.jdbc;


import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

import org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement;

import com.sorin.idea.dao.*;
import com.sorin.idea.dto.*;
import com.sorin.idea.exceptions.*;
import com.sorin.idea.factory.*;
import com.sorin.idea.util.UtilCodifi;

import oracle.jdbc.OracleTypes;


public class ArrEstudioTaquiDaoImpl extends AbstractDAO implements ArrEstudioTaquiDao
{
	private AuditoriaDao auditoriaDao = new AuditoriaDao();
    private AuditoriaDto auditoriaDto = null;
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT IDESTUDIO, IDTAQUI, NUMTAQUI, INDUCCION, TAQUIINDU, NUMNOCLIN, COMPORTAMIENTO, IDN1, IDN2, IDN3, PUNTOEST, MODOIND, PROTOCOLO, LCTREN, NEXTRA, AAVV, FARMACOS, COMENTARIOS, VALORIND, PUNTOEST2, MODOIND2, VALORIND2, LONGCICLO, MORFOLOGIA FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( IDESTUDIO, IDTAQUI, NUMTAQUI, INDUCCION, TAQUIINDU, NUMNOCLIN, COMPORTAMIENTO, IDN1, IDN2, IDN3, PUNTOEST, MODOIND, PROTOCOLO, LCTREN, NEXTRA, AAVV, FARMACOS, COMENTARIOS, VALORIND, PUNTOEST2, MODOIND2, VALORIND2, LONGCICLO, MORFOLOGIA ) VALUES ( ?, null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET IDESTUDIO = ?, IDTAQUI = ?, NUMTAQUI = ?, INDUCCION = ?, TAQUIINDU = ?, NUMNOCLIN = ?, COMPORTAMIENTO = ?, IDN1 = ?, IDN2 = ?, IDN3 = ?, PUNTOEST = ?, MODOIND = ?, PROTOCOLO = ?, LCTREN = ?, NEXTRA = ?, AAVV = ?, FARMACOS = ?, COMENTARIOS = ?, VALORIND = ?, PUNTOEST2 = ?, MODOIND2 = ?, VALORIND2 = ?, LONGCICLO = ?, MORFOLOGIA = ? WHERE IDESTUDIO = ? AND IDTAQUI = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE IDESTUDIO = ? AND IDTAQUI = ?";
	protected final String SQL_DELETE_CHICO = "DELETE FROM " + getTableName() + " WHERE IDESTUDIO = ?";

	/** 
	 * Index of column IDESTUDIO
	 */
	protected static final int COLUMN_IDESTUDIO = 1;

	/** 
	 * Index of column IDTAQUI
	 */
	protected static final int COLUMN_IDTAQUI = 2;

	/** 
	 * Index of column NUMTAQUI
	 */
	protected static final int COLUMN_NUMTAQUI = 3;

	/** 
	 * Index of column INDUCCION
	 */
	protected static final int COLUMN_INDUCCION = 4;

	/** 
	 * Index of column TAQUIINDU
	 */
	protected static final int COLUMN_TAQUIINDU = 5;

	/** 
	 * Index of column NUMNOCLIN
	 */
	protected static final int COLUMN_NUMNOCLIN = 6;

	/** 
	 * Index of column COMPORTAMIENTO
	 */
	protected static final int COLUMN_COMPORTAMIENTO = 7;

	/** 
	 * Index of column IDN1
	 */
	protected static final int COLUMN_IDN1 = 8;

	/** 
	 * Index of column IDN2
	 */
	protected static final int COLUMN_IDN2 = 9;

	/** 
	 * Index of column IDN3
	 */
	protected static final int COLUMN_IDN3 = 10;

	/** 
	 * Index of column PUNTOEST
	 */
	protected static final int COLUMN_PUNTOEST = 11;

	/** 
	 * Index of column MODOIND
	 */
	protected static final int COLUMN_MODOIND = 12;

	/** 
	 * Index of column PROTOCOLO
	 */
	protected static final int COLUMN_PROTOCOLO = 13;

	/** 
	 * Index of column LCTREN
	 */
	protected static final int COLUMN_LCTREN = 14;

	/** 
	 * Index of column NEXTRA
	 */
	protected static final int COLUMN_NEXTRA = 15;

	/** 
	 * Index of column AAVV
	 */
	protected static final int COLUMN_AAVV = 16;

	/** 
	 * Index of column FARMACOS
	 */
	protected static final int COLUMN_FARMACOS = 17;

	/** 
	 * Index of column COMENTARIOS
	 */
	protected static final int COLUMN_COMENTARIOS = 18;
	
	protected static final int COLUMN_VALORIND = 19;
	
	protected static final int COLUMN_PUNTOEST2 = 20;
	protected static final int COLUMN_MODOIND2 = 21;
	protected static final int COLUMN_VALORIND2 = 22;
	protected static final int COLUMN_LONGCICLO = 23; 
	protected static final int COLUMN_MORFOLOGIA = 24; 

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 24;

	/** 
	 * Index of primary-key column IDESTUDIO
	 */
	protected static final int PK_COLUMN_IDESTUDIO = 1;

	/** 
	 * Index of primary-key column IDTAQUI
	 */
	protected static final int PK_COLUMN_IDTAQUI = 2;

	/** 
	 * Inserts a new row in the ARR_ESTUDIO_TAQUI table.
	 */
	public ArrEstudioTaquiPk insert(ArrEstudioTaqui dto) throws ArrEstudioTaquiDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			
			int index = 1;
			if (dto.getIdestudio() != null) {
				stmt.setInt( index++, dto.getIdestudio().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getNumtaqui() != null) {
				stmt.setInt( index++, dto.getNumtaqui().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getInduccion() != null) {
				stmt.setInt( index++, dto.getInduccion().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getTaquiindu() != null) {
				stmt.setInt( index++, dto.getTaquiindu().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getNumnoclin() );
			if (dto.getComportamiento() != null) {
				stmt.setInt( index++, dto.getComportamiento().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdn1() != null) {
				stmt.setInt( index++, dto.getIdn1().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdn2() != null) {
				stmt.setInt( index++, dto.getIdn2().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdn3() != null) {
				stmt.setInt( index++, dto.getIdn3().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getPuntoest() != null) {
				stmt.setInt( index++, dto.getPuntoest().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getModoind() != null) {
				stmt.setInt( index++, dto.getModoind().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getProtocolo() != null) {
				stmt.setInt( index++, dto.getProtocolo().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getLctren() );
			stmt.setString( index++, dto.getNextra() );
			if (dto.getAavv() != null) {
				stmt.setInt( index++, dto.getAavv().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getFarmacos() );
			stmt.setString( index++, dto.getComentarios() );
			stmt.setString( index++, dto.getValorind() );
			if (dto.getPuntoest2() != null) {
				stmt.setInt( index++, dto.getPuntoest2().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getModoind2() != null) {
				stmt.setInt( index++, dto.getModoind2().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
			stmt.setString( index++, dto.getValorind2() );
			stmt.setString( index++, dto.getLongciclo() );
			if (dto.getMorfologia() != null) {
				stmt.setInt( index++, dto.getMorfologia().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}

			int rows = stmt.executeUpdate();
			stmt = null;
			stmt = conn.prepareStatement("SELECT LAST_INSERT_ID() id");
			ResultSet a = stmt.executeQuery();
			while (a.next()) {
				dto.setIdtaqui((int) a.getLong(1));
			}
			long t2 = System.currentTimeMillis();
			auditoriaDto.setAccion(AuditoriaDto.insercion);
	        auditoriaDto.setDescri(dto.toString());
	        auditoriaDao.escribeAuditoria(auditoriaDto);
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			throw new ArrEstudioTaquiDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the ARR_ESTUDIO_TAQUI table.
	 */
	public void update(ArrEstudioTaquiPk pk, ArrEstudioTaqui dto) throws ArrEstudioTaquiDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			if (dto.getIdestudio() != null) {
				stmt.setInt( index++, dto.getIdestudio().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdtaqui() != null) {
				stmt.setInt( index++, dto.getIdtaqui().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getNumtaqui() != null) {
				stmt.setInt( index++, dto.getNumtaqui().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getInduccion() != null) {
				stmt.setInt( index++, dto.getInduccion().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getTaquiindu() != null) {
				stmt.setInt( index++, dto.getTaquiindu().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getNumnoclin() );
			if (dto.getComportamiento() != null) {
				stmt.setInt( index++, dto.getComportamiento().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdn1() != null) {
				stmt.setInt( index++, dto.getIdn1().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdn2() != null) {
				stmt.setInt( index++, dto.getIdn2().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getIdn3() != null) {
				stmt.setInt( index++, dto.getIdn3().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getPuntoest() != null) {
				stmt.setInt( index++, dto.getPuntoest().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getModoind() != null) {
				stmt.setInt( index++, dto.getModoind().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getProtocolo() != null) {
				stmt.setInt( index++, dto.getProtocolo().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getLctren() );
			stmt.setString( index++, dto.getNextra() );
			if (dto.getAavv() != null) {
				stmt.setInt( index++, dto.getAavv().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getFarmacos() );
			stmt.setString( index++, dto.getComentarios() );
			stmt.setString( index++, dto.getValorind() );
			if (dto.getPuntoest2() != null) {
				stmt.setInt( index++, dto.getPuntoest2().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getModoind2() != null) {
				stmt.setInt( index++, dto.getModoind2().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
			stmt.setString( index++, dto.getValorind2() );
			stmt.setString( index++, dto.getLongciclo() );
			if (dto.getMorfologia() != null) {
				stmt.setInt( index++, dto.getMorfologia().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
			if (pk.getIdestudio() != null) {
				stmt.setInt( 25, pk.getIdestudio().intValue() );
			} else {
				stmt.setNull(25, java.sql.Types.INTEGER);
			}
		
			if (pk.getIdtaqui() != null) {
				stmt.setInt( 26, pk.getIdtaqui().intValue() );
			} else {
				stmt.setNull(26, java.sql.Types.INTEGER);
			}
		
			int rows = stmt.executeUpdate();
			auditoriaDto.setAccion(AuditoriaDto.modificacion);
	        auditoriaDto.setDescri(dto.toString());
	        auditoriaDao.escribeAuditoria(auditoriaDto);
			reset(dto);
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new ArrEstudioTaquiDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the ARR_ESTUDIO_TAQUI table.
	 */
	public void delete(ArrEstudioTaquiPk pk) throws ArrEstudioTaquiDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE );
			if (pk.getIdestudio() != null) {
				stmt.setInt( 1, pk.getIdestudio().intValue() );
			} else {
				stmt.setNull(1, java.sql.Types.INTEGER);
			}
		
			if (pk.getIdtaqui() != null) {
				stmt.setInt( 2, pk.getIdtaqui().intValue() );
			} else {
				stmt.setNull(2, java.sql.Types.INTEGER);
			}
		
			int rows = stmt.executeUpdate();
			auditoriaDto.setAccion(AuditoriaDto.borrado);
	        auditoriaDto.setDescri(pk.toString());
	        auditoriaDao.escribeAuditoria(auditoriaDto);
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new ArrEstudioTaquiDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}
	
	public void delete(Integer idestudio) throws ArrEstudioTaquiDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE_CHICO );
			if (idestudio != null) {
				stmt.setInt( 1, idestudio.intValue() );
			} else {
				stmt.setNull(1, java.sql.Types.INTEGER);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new ArrEstudioTaquiDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}	
	}

	/** 
	 * Returns the rows from the ARR_ESTUDIO_TAQUI table that matches the specified primary-key value.
	 */
	public ArrEstudioTaqui findByPrimaryKey(ArrEstudioTaquiPk pk) throws ArrEstudioTaquiDaoException
	{
		return findByPrimaryKey( pk.getIdestudio(), pk.getIdtaqui() );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'IDESTUDIO = :idestudio AND IDTAQUI = :idtaqui'.
	 */
	public ArrEstudioTaqui findByPrimaryKey(Integer idestudio, Integer idtaqui) throws ArrEstudioTaquiDaoException
	{
		ArrEstudioTaqui ret[] = findByDynamicSelect( SQL_SELECT + " WHERE IDESTUDIO = ? AND IDTAQUI = ?", new Object[] { idestudio, idtaqui } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria ''.
	 */
	public ArrEstudioTaqui[] findAll() throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY IDESTUDIO, IDTAQUI", null );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'IDESTUDIO = :idestudio'.
	 */
	public ArrEstudioTaqui[] findWhereIdestudioEquals(long idestudio) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDESTUDIO = ? ORDER BY NUMTAQUI DESC", new Object[] {  new Long(idestudio) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'IDTAQUI = :idtaqui'.
	 */
	public ArrEstudioTaqui[] findWhereIdtaquiEquals(long idtaqui) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDTAQUI = ? ORDER BY IDTAQUI", new Object[] {  new Long(idtaqui) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'NUMTAQUI = :numtaqui'.
	 */
	public ArrEstudioTaqui[] findWhereNumtaquiEquals(long numtaqui) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NUMTAQUI = ? ORDER BY NUMTAQUI", new Object[] {  new Long(numtaqui) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'INDUCCION = :induccion'.
	 */
	public ArrEstudioTaqui[] findWhereInduccionEquals(long induccion) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE INDUCCION = ? ORDER BY INDUCCION", new Object[] {  new Long(induccion) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'TAQUIINDU = :taquiindu'.
	 */
	public ArrEstudioTaqui[] findWhereTaquiinduEquals(long taquiindu) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE TAQUIINDU = ? ORDER BY TAQUIINDU", new Object[] {  new Long(taquiindu) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'NUMNOCLIN = :numnoclin'.
	 */
	public ArrEstudioTaqui[] findWhereNumnoclinEquals(String numnoclin) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NUMNOCLIN = ? ORDER BY NUMNOCLIN", new Object[] { numnoclin } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'COMPORTAMIENTO = :comportamiento'.
	 */
	public ArrEstudioTaqui[] findWhereComportamientoEquals(long comportamiento) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE COMPORTAMIENTO = ? ORDER BY COMPORTAMIENTO", new Object[] {  new Long(comportamiento) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'IDN1 = :idn1'.
	 */
	public ArrEstudioTaqui[] findWhereIdn1Equals(long idn1) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDN1 = ? ORDER BY IDN1", new Object[] {  new Long(idn1) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'IDN2 = :idn2'.
	 */
	public ArrEstudioTaqui[] findWhereIdn2Equals(long idn2) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDN2 = ? ORDER BY IDN2", new Object[] {  new Long(idn2) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'IDN3 = :idn3'.
	 */
	public ArrEstudioTaqui[] findWhereIdn3Equals(long idn3) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDN3 = ? ORDER BY IDN3", new Object[] {  new Long(idn3) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'PUNTOEST = :puntoest'.
	 */
	public ArrEstudioTaqui[] findWherePuntoestEquals(long puntoest) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PUNTOEST = ? ORDER BY PUNTOEST", new Object[] {  new Long(puntoest) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'MODOIND = :modoind'.
	 */
	public ArrEstudioTaqui[] findWhereModoindEquals(long modoind) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MODOIND = ? ORDER BY MODOIND", new Object[] {  new Long(modoind) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'PROTOCOLO = :protocolo'.
	 */
	public ArrEstudioTaqui[] findWhereProtocoloEquals(long protocolo) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROTOCOLO = ? ORDER BY PROTOCOLO", new Object[] {  new Long(protocolo) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'LCTREN = :lctren'.
	 */
	public ArrEstudioTaqui[] findWhereLctrenEquals(String lctren) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE LCTREN = ? ORDER BY LCTREN", new Object[] { lctren } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'NEXTRA = :nextra'.
	 */
	public ArrEstudioTaqui[] findWhereNextraEquals(String nextra) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NEXTRA = ? ORDER BY NEXTRA", new Object[] { nextra } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'AAVV = :aavv'.
	 */
	public ArrEstudioTaqui[] findWhereAavvEquals(long aavv) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE AAVV = ? ORDER BY AAVV", new Object[] {  new Long(aavv) } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'FARMACOS = :farmacos'.
	 */
	public ArrEstudioTaqui[] findWhereFarmacosEquals(String farmacos) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FARMACOS = ? ORDER BY FARMACOS", new Object[] { farmacos } );
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the criteria 'COMENTARIOS = :comentarios'.
	 */
	public ArrEstudioTaqui[] findWhereComentariosEquals(String comentarios) throws ArrEstudioTaquiDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE COMENTARIOS = ? ORDER BY COMENTARIOS", new Object[] { comentarios } );
	}

	/**
	 * Method 'ArrEstudioTaquiDaoImpl'
	 * 
	 */
	public ArrEstudioTaquiDaoImpl(String usuario)
	{
		this.auditoriaDto = new AuditoriaDto(usuario, getTableName());
	}
	public ArrEstudioTaquiDaoImpl(final java.sql.Connection userConn,String usuario)
	{
		this.userConn = userConn;
		this.auditoriaDto = new AuditoriaDto(usuario, getTableName());
	}

	/**
	 * Method 'ArrEstudioTaquiDaoImpl'
	 * 
	 * @param userConn
	 */
	public ArrEstudioTaquiDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		//return "idea.ARR_ESTUDIO_TAQUI";
		return "idea.arr_estudio_taqui";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ArrEstudioTaqui fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ArrEstudioTaqui dto = new ArrEstudioTaqui();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ArrEstudioTaqui[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ArrEstudioTaqui dto = new ArrEstudioTaqui();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ArrEstudioTaqui ret[] = new ArrEstudioTaqui[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ArrEstudioTaqui dto, ResultSet rs) throws SQLException
	{
		dto.setIdestudio( new Integer( rs.getInt(COLUMN_IDESTUDIO) ) );
		dto.setIdtaqui( new Integer( rs.getInt(COLUMN_IDTAQUI) ) );
		dto.setNumtaqui( new Integer( rs.getInt(COLUMN_NUMTAQUI) ) );
		if (rs.wasNull()) {
			dto.setNumtaqui( null );
		}
		
		dto.setInduccion( new Integer( rs.getInt(COLUMN_INDUCCION) ) );
		if (rs.wasNull()) {
			dto.setInduccion( null );
		}
		
		dto.setTaquiindu( new Integer( rs.getInt(COLUMN_TAQUIINDU) ) );
		if (rs.wasNull()) {
			dto.setTaquiindu( null );
		}
		
		dto.setNumnoclin( rs.getString( COLUMN_NUMNOCLIN ) );
		dto.setComportamiento( new Integer( rs.getInt(COLUMN_COMPORTAMIENTO) ) );
		if (rs.wasNull()) {
			dto.setComportamiento( null );
		}
		
		dto.setIdn1( new Integer( rs.getInt(COLUMN_IDN1) ) );
		if (rs.wasNull()) {
			dto.setIdn1( null );
		}
		
		dto.setIdn2( new Integer( rs.getInt(COLUMN_IDN2) ) );
		if (rs.wasNull()) {
			dto.setIdn2( null );
		}
		
		dto.setIdn3( new Integer( rs.getInt(COLUMN_IDN3) ) );
		if (rs.wasNull()) {
			dto.setIdn3( null );
		}
		
		dto.setPuntoest( new Integer( rs.getInt(COLUMN_PUNTOEST) ) );
		if (rs.wasNull()) {
			dto.setPuntoest( null );
		}
		
		dto.setModoind( new Integer( rs.getInt(COLUMN_MODOIND) ) );
		if (rs.wasNull()) {
			dto.setModoind( null );
		}
		
		dto.setProtocolo( new Integer( rs.getInt(COLUMN_PROTOCOLO) ) );
		if (rs.wasNull()) {
			dto.setProtocolo( null );
		}
		
		dto.setLctren( rs.getString( COLUMN_LCTREN ) );
		dto.setNextra( rs.getString( COLUMN_NEXTRA ) );
		dto.setAavv( new Integer( rs.getInt(COLUMN_AAVV) ) );
		if (rs.wasNull()) {
			dto.setAavv( null );
		}
		
		dto.setFarmacos( rs.getString( COLUMN_FARMACOS ) );
		dto.setComentarios( rs.getString( COLUMN_COMENTARIOS ) );
		dto.setValorind( rs.getString( COLUMN_VALORIND ) );
		
		dto.setPuntoest2( new Integer( rs.getInt(COLUMN_PUNTOEST2) ) );
		if (rs.wasNull()) {
			dto.setPuntoest2( null );
		}
		
		dto.setModoind2( new Integer( rs.getInt(COLUMN_MODOIND2) ) );
		if (rs.wasNull()) {
			dto.setModoind2( null );
		}
		dto.setValorind2( rs.getString( COLUMN_VALORIND2 ) );
		dto.setLongciclo( rs.getString( COLUMN_LONGCICLO ) );
		dto.setMorfologia( new Integer( rs.getInt(COLUMN_MORFOLOGIA) ) );
		if (rs.wasNull()) {
			dto.setMorfologia( null );
		}
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ArrEstudioTaqui dto)
	{
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the specified arbitrary SQL statement
	 */
	public ArrEstudioTaqui[] findByDynamicSelect(String sql, Object[] sqlParams) throws ArrEstudioTaquiDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new ArrEstudioTaquiDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the ARR_ESTUDIO_TAQUI table that match the specified arbitrary SQL statement
	 */
	public ArrEstudioTaqui[] findByDynamicWhere(String sql, Object[] sqlParams) throws ArrEstudioTaquiDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new ArrEstudioTaquiDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}
	
	/** 
	 * Devuelve la consulta estadística de las taquicardias
	 */
	public ArrayList<ArrayList<Object>> getEstadisticas(String nhcs, String eefs) throws ArrEstudioTaquiDaoException{
		StringBuffer sql = new StringBuffer();
		
		sql.append("select pac.nhc PACIENTE,");
		sql.append("ee.nestudio NESTUDIO,");
		sql.append("taq.numtaqui NUMERO,");
		sql.append("taq.longciclo LC,");
		sql.append("m1.valor MORFOLOGIA,");
		sql.append("taq.induccion INDUCCION,");
		sql.append("taq.taquiindu CLINICA,");
		sql.append("taq.comportamiento COMPORTAMIENTO,");
		sql.append("taq.idn1 TIPO");		
		sql.append(" from arr_pacientes pac, arr_estudio ee,");
		sql.append(" arr_estudio_taqui taq");
		sql.append(" LEFT OUTER JOIN arr_maestras m1 ON taq.morfologia = m1.codigo");
		sql.append(" WHERE pac.codigo = ee.idpaciente");
		sql.append(" AND ee.idestudio = taq.idestudio");
		if(nhcs.length()>0)
			sql.append(" and pac.nhc in " + nhcs);
		if(eefs.length()>0)
			sql.append(" and ee.idestudio in " + eefs);
		sql.append(" ORDER BY 1");
		
		return findByDynamicSelect(sql.toString());
	}
	
	public ArrayList<ArrayList<Object>> findByDynamicSelect(String sql) throws ArrEstudioTaquiDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return UtilCodifi.Results2Array(rs);
		}
		catch (Exception _e) {
			throw new ArrEstudioTaquiDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
