/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.jdbc;

import com.sorin.idea.dao.*;
import com.sorin.idea.factory.*;
import java.util.Date;
import com.sorin.idea.dto.*;
import com.sorin.idea.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class IntElectrodosDaoImpl extends AbstractDAO implements IntElectrodosDao
{
	private AuditoriaDao auditoriaDao = new AuditoriaDao();
    private AuditoriaDto auditoriaDto = null;
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT IDINTEGRACION, MODELO, NSERIE, FABRICANTE, CAMARA, ZONA, ESTADO, FECHAIMPLANTE FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( IDINTEGRACION, MODELO, NSERIE, FABRICANTE, CAMARA, ZONA, ESTADO, FECHAIMPLANTE ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET IDINTEGRACION = ?, MODELO = ?, NSERIE = ?, FABRICANTE = ?, CAMARA = ?, ZONA = ?, ESTADO = ?, FECHAIMPLANTE = ? WHERE IDINTEGRACION = ? AND MODELO = ? AND NSERIE = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE IDINTEGRACION = ? AND MODELO = ? AND NSERIE = ?";

	/** 
	 * Index of column IDINTEGRACION
	 */
	protected static final int COLUMN_IDINTEGRACION = 1;

	/** 
	 * Index of column MODELO
	 */
	protected static final int COLUMN_MODELO = 2;

	/** 
	 * Index of column NSERIE
	 */
	protected static final int COLUMN_NSERIE = 3;

	/** 
	 * Index of column FABRICANTE
	 */
	protected static final int COLUMN_FABRICANTE = 4;

	/** 
	 * Index of column CAMARA
	 */
	protected static final int COLUMN_CAMARA = 5;

	/** 
	 * Index of column ZONA
	 */
	protected static final int COLUMN_ZONA = 6;

	/** 
	 * Index of column ESTADO
	 */
	protected static final int COLUMN_ESTADO = 7;

	/** 
	 * Index of column FECHAIMPLANTE
	 */
	protected static final int COLUMN_FECHAIMPLANTE = 8;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 8;

	/** 
	 * Index of primary-key column IDINTEGRACION
	 */
	protected static final int PK_COLUMN_IDINTEGRACION = 1;

	/** 
	 * Index of primary-key column MODELO
	 */
	protected static final int PK_COLUMN_MODELO = 2;

	/** 
	 * Index of primary-key column NSERIE
	 */
	protected static final int PK_COLUMN_NSERIE = 3;

	/** 
	 * Inserts a new row in the int_electrodos table.
	 */
	public IntElectrodosPk insert(IntElectrodos dto) throws IntElectrodosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			if (dto.getIdintegracion() != null) {
				stmt.setInt( index++, dto.getIdintegracion().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getModelo() );
			stmt.setString( index++, dto.getNserie() );
			stmt.setString( index++, dto.getFabricante() );
			if (dto.getCamara() != null) {
				stmt.setInt( index++, dto.getCamara().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getZona() != null) {
				stmt.setInt( index++, dto.getZona().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getEstado() != null) {
				stmt.setInt( index++, dto.getEstado().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setDate(index++, dto.getFechaimplante()==null ? null : new java.sql.Date( dto.getFechaimplante().getTime() ) );
			//System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			//System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			auditoriaDto.setAccion(AuditoriaDto.insercion);
			auditoriaDto.setDescri(dto.toString());
			auditoriaDao.escribeAuditoria(auditoriaDto);
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new IntElectrodosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the int_electrodos table.
	 */
	public void update(IntElectrodosPk pk, IntElectrodos dto) throws IntElectrodosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			//System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			if (dto.getIdintegracion() != null) {
				stmt.setInt( index++, dto.getIdintegracion().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getModelo() );
			stmt.setString( index++, dto.getNserie() );
			stmt.setString( index++, dto.getFabricante() );
			if (dto.getCamara() != null) {
				stmt.setInt( index++, dto.getCamara().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getZona() != null) {
				stmt.setInt( index++, dto.getZona().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			if (dto.getEstado() != null) {
				stmt.setInt( index++, dto.getEstado().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setDate(index++, dto.getFechaimplante()==null ? null : new java.sql.Date( dto.getFechaimplante().getTime() ) );
			if (pk.getIdintegracion() != null) {
				stmt.setInt( 9, pk.getIdintegracion().intValue() );
			} else {
				stmt.setNull(9, java.sql.Types.INTEGER);
			}
		
			stmt.setString( 10, pk.getModelo() );
			stmt.setString( 11, pk.getNserie() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			auditoriaDto.setAccion(AuditoriaDto.modificacion);
			auditoriaDto.setDescri(dto.toString());
			auditoriaDao.escribeAuditoria(auditoriaDto);
			//System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new IntElectrodosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the int_electrodos table.
	 */
	public void delete(IntElectrodosPk pk) throws IntElectrodosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			//System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			if (pk.getIdintegracion() != null) {
				stmt.setInt( 1, pk.getIdintegracion().intValue() );
			} else {
				stmt.setNull(1, java.sql.Types.INTEGER);
			}
		
			stmt.setString( 2, pk.getModelo() );
			stmt.setString( 3, pk.getNserie() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			//System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			auditoriaDto.setAccion(AuditoriaDto.borrado);
			auditoriaDto.setDescri(pk.toString());
			auditoriaDao.escribeAuditoria(auditoriaDto);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new IntElectrodosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the int_electrodos table that matches the specified primary-key value.
	 */
	public IntElectrodos findByPrimaryKey(IntElectrodosPk pk) throws IntElectrodosDaoException
	{
		return findByPrimaryKey( pk.getIdintegracion(), pk.getModelo(), pk.getNserie() );
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria 'IDINTEGRACION = :idintegracion AND MODELO = :modelo AND NSERIE = :nserie'.
	 */
	public IntElectrodos findByPrimaryKey(Integer idintegracion, String modelo, String nserie) throws IntElectrodosDaoException
	{
		IntElectrodos ret[] = findByDynamicSelect( SQL_SELECT + " WHERE IDINTEGRACION = ? AND MODELO = ? AND NSERIE = ?", new Object[] { idintegracion, modelo, nserie } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria ''.
	 */
	public IntElectrodos[] findAll() throws IntElectrodosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY IDINTEGRACION, MODELO, NSERIE", null );
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria 'IDINTEGRACION = :idintegracion'.
	 */
	public IntElectrodos[] findWhereIdintegracionEquals(int idintegracion) throws IntElectrodosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDINTEGRACION = ? ORDER BY IDINTEGRACION", new Object[] {  new Integer(idintegracion) } );
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria 'MODELO = :modelo'.
	 */
	public IntElectrodos[] findWhereModeloEquals(String modelo) throws IntElectrodosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MODELO = ? ORDER BY MODELO", new Object[] { modelo } );
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria 'NSERIE = :nserie'.
	 */
	public IntElectrodos[] findWhereNserieEquals(String nserie) throws IntElectrodosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NSERIE = ? ORDER BY NSERIE", new Object[] { nserie } );
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria 'FABRICANTE = :fabricante'.
	 */
	public IntElectrodos[] findWhereFabricanteEquals(String fabricante) throws IntElectrodosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FABRICANTE = ? ORDER BY FABRICANTE", new Object[] { fabricante } );
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria 'CAMARA = :camara'.
	 */
	public IntElectrodos[] findWhereCamaraEquals(int camara) throws IntElectrodosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CAMARA = ? ORDER BY CAMARA", new Object[] {  new Integer(camara) } );
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria 'ZONA = :zona'.
	 */
	public IntElectrodos[] findWhereZonaEquals(int zona) throws IntElectrodosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ZONA = ? ORDER BY ZONA", new Object[] {  new Integer(zona) } );
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria 'ESTADO = :estado'.
	 */
	public IntElectrodos[] findWhereEstadoEquals(int estado) throws IntElectrodosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ESTADO = ? ORDER BY ESTADO", new Object[] {  new Integer(estado) } );
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the criteria 'FECHAIMPLANTE = :fechaimplante'.
	 */
	public IntElectrodos[] findWhereFechaimplanteEquals(Date fechaimplante) throws IntElectrodosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHAIMPLANTE = ? ORDER BY FECHAIMPLANTE", new Object[] { fechaimplante==null ? null : new java.sql.Date( fechaimplante.getTime() ) } );
	}

	/**
	 * Method 'IntElectrodosDaoImpl'
	 * 
	 */
	public IntElectrodosDaoImpl()
	{
	}
	
	public IntElectrodosDaoImpl(String usuario)
	{
		this.auditoriaDto = new AuditoriaDto(usuario, getTableName());
	}
	public IntElectrodosDaoImpl(final java.sql.Connection userConn,String usuario)
	{
		this.userConn = userConn;
		this.auditoriaDto = new AuditoriaDto(usuario, getTableName());
	}

	/**
	 * Method 'IntElectrodosDaoImpl'
	 * 
	 * @param userConn
	 */
	public IntElectrodosDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "idea.int_electrodos";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected IntElectrodos fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			IntElectrodos dto = new IntElectrodos();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected IntElectrodos[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			IntElectrodos dto = new IntElectrodos();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		IntElectrodos ret[] = new IntElectrodos[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(IntElectrodos dto, ResultSet rs) throws SQLException
	{
		dto.setIdintegracion( new Integer( rs.getInt(COLUMN_IDINTEGRACION) ) );
		dto.setModelo( rs.getString( COLUMN_MODELO ) );
		dto.setNserie( rs.getString( COLUMN_NSERIE ) );
		dto.setFabricante( rs.getString( COLUMN_FABRICANTE ) );
		dto.setCamara( new Integer( rs.getInt(COLUMN_CAMARA) ) );
		if (rs.wasNull()) {
			dto.setCamara( null );
		}
		
		dto.setZona( new Integer( rs.getInt(COLUMN_ZONA) ) );
		if (rs.wasNull()) {
			dto.setZona( null );
		}
		
		dto.setEstado( new Integer( rs.getInt(COLUMN_ESTADO) ) );
		if (rs.wasNull()) {
			dto.setEstado( null );
		}
		
		dto.setFechaimplante( rs.getDate(COLUMN_FECHAIMPLANTE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(IntElectrodos dto)
	{
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the specified arbitrary SQL statement
	 */
	public IntElectrodos[] findByDynamicSelect(String sql, Object[] sqlParams) throws IntElectrodosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			//System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new IntElectrodosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the int_electrodos table that match the specified arbitrary SQL statement
	 */
	public IntElectrodos[] findByDynamicWhere(String sql, Object[] sqlParams) throws IntElectrodosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			//System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new IntElectrodosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
