/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.jdbc;

import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

import com.sorin.idea.dao.*;
import com.sorin.idea.dto.*;
import com.sorin.idea.exceptions.*;
import com.sorin.idea.factory.*;

public class SegSintomasDaoImpl extends AbstractDAO implements SegSintomasDao
{
	private AuditoriaDao auditoriaDao = new AuditoriaDao();
    private AuditoriaDto auditoriaDto = null;
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT IDSITCLIN, IDSINTOMA FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( IDSITCLIN, IDSINTOMA ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET IDSITCLIN = ?, IDSINTOMA = ? WHERE IDSITCLIN = ? AND IDSINTOMA = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE IDSITCLIN = ? ";

	/** 
	 * Index of column IDSITCLIN
	 */
	protected static final int COLUMN_IDSITCLIN = 1;

	/** 
	 * Index of column IDSINTOMA
	 */
	protected static final int COLUMN_IDSINTOMA = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column IDSITCLIN
	 */
	protected static final int PK_COLUMN_IDSITCLIN = 1;

	/** 
	 * Index of primary-key column IDSINTOMA
	 */
	protected static final int PK_COLUMN_IDSINTOMA = 2;

	/** 
	 * Inserts a new row in the seg_sintomas table.
	 */
	public SegSintomasPk insert(SegSintomas dto) throws SegSintomasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			if (dto.getIdsitclin() != null) {
				stmt.setInt( index++, dto.getIdsitclin().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getIdsintoma() );
			//System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			//System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			auditoriaDto.setAccion(AuditoriaDto.insercion);
			auditoriaDto.setDescri(dto.toString());
			auditoriaDao.escribeAuditoria(auditoriaDto);
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SegSintomasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the seg_sintomas table.
	 */
	public void update(SegSintomasPk pk, SegSintomas dto) throws SegSintomasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			//System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			if (dto.getIdsitclin() != null) {
				stmt.setInt( index++, dto.getIdsitclin().intValue() );
			} else {
				stmt.setNull(index++, java.sql.Types.INTEGER);
			}
		
			stmt.setString( index++, dto.getIdsintoma() );
			if (pk.getIdsitclin() != null) {
				stmt.setInt( 3, pk.getIdsitclin().intValue() );
			} else {
				stmt.setNull(3, java.sql.Types.INTEGER);
			}
		
			stmt.setString( 4, pk.getIdsintoma() );
			int rows = stmt.executeUpdate();
			auditoriaDto.setAccion(AuditoriaDto.modificacion);
			auditoriaDto.setDescri(dto.toString());
			auditoriaDao.escribeAuditoria(auditoriaDto);
			reset(dto);
			long t2 = System.currentTimeMillis();
			//System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SegSintomasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the seg_sintomas table.
	 */
	public void delete(SegSintomasPk pk) throws SegSintomasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			//System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			if (pk.getIdsitclin() != null) {
				stmt.setInt( 1, pk.getIdsitclin().intValue() );
			} else {
				stmt.setNull(1, java.sql.Types.INTEGER);
			}
		
			//stmt.setString( 2, pk.getIdsintoma() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			//System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			auditoriaDto.setAccion(AuditoriaDto.borrado);
			auditoriaDto.setDescri(pk.toString());
			auditoriaDao.escribeAuditoria(auditoriaDto);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SegSintomasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the seg_sintomas table that matches the specified primary-key value.
	 */
	public SegSintomas findByPrimaryKey(SegSintomasPk pk) throws SegSintomasDaoException
	{
		return findByPrimaryKey( pk.getIdsitclin(), pk.getIdsintoma() );
	}

	/** 
	 * Returns all rows from the seg_sintomas table that match the criteria 'IDSITCLIN = :idsitclin AND IDSINTOMA = :idsintoma'.
	 */
	public SegSintomas findByPrimaryKey(Integer idsitclin, String idsintoma) throws SegSintomasDaoException
	{
		SegSintomas ret[] = findByDynamicSelect( SQL_SELECT + " WHERE IDSITCLIN = ? AND IDSINTOMA = ?", new Object[] { idsitclin, idsintoma } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the seg_sintomas table that match the criteria ''.
	 */
	public SegSintomas[] findAll() throws SegSintomasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY IDSITCLIN, IDSINTOMA", null );
	}

	/** 
	 * Returns all rows from the seg_sintomas table that match the criteria 'IDSITCLIN = :idsitclin'.
	 */
	public SegSintomas[] findBySegSituacionclinica(int idsitclin) throws SegSintomasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDSITCLIN = ?", new Object[] {  new Integer(idsitclin) } );
	}

	/** 
	 * Returns all rows from the seg_sintomas table that match the criteria 'IDSITCLIN = :idsitclin'.
	 */
	public SegSintomas[] findWhereIdsitclinEquals(int idsitclin) throws SegSintomasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDSITCLIN = ? ORDER BY IDSITCLIN", new Object[] {  new Integer(idsitclin) } );
	}

	/** 
	 * Returns all rows from the seg_sintomas table that match the criteria 'IDSINTOMA = :idsintoma'.
	 */
	public SegSintomas[] findWhereIdsintomaEquals(String idsintoma) throws SegSintomasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IDSINTOMA = ? ORDER BY IDSINTOMA", new Object[] { idsintoma } );
	}

	/**
	 * Method 'SegSintomasDaoImpl'
	 * 
	 */
	public SegSintomasDaoImpl()
	{
	}
	/**
	 * Method 'SegSintomasDaoImpl'
	 * 
	 */
	public SegSintomasDaoImpl(String usuario)
	{
		this.auditoriaDto = new AuditoriaDto(usuario, getTableName());
	}
	public SegSintomasDaoImpl(final java.sql.Connection userConn,String usuario)
	{
		this.userConn = userConn;
		this.auditoriaDto = new AuditoriaDto(usuario, getTableName());
	}

	/**
	 * Method 'SegSintomasDaoImpl'
	 * 
	 * @param userConn
	 */
	public SegSintomasDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "idea.seg_sintomas";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected SegSintomas fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			SegSintomas dto = new SegSintomas();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected SegSintomas[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			SegSintomas dto = new SegSintomas();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		SegSintomas ret[] = new SegSintomas[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(SegSintomas dto, ResultSet rs) throws SQLException
	{
		dto.setIdsitclin( new Integer( rs.getInt(COLUMN_IDSITCLIN) ) );
		dto.setIdsintoma( rs.getString( COLUMN_IDSINTOMA ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(SegSintomas dto)
	{
	}

	/** 
	 * Returns all rows from the seg_sintomas table that match the specified arbitrary SQL statement
	 */
	public SegSintomas[] findByDynamicSelect(String sql, Object[] sqlParams) throws SegSintomasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			//System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SegSintomasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the seg_sintomas table that match the specified arbitrary SQL statement
	 */
	public SegSintomas[] findByDynamicWhere(String sql, Object[] sqlParams) throws SegSintomasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			//System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SegSintomasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
