/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import java.io.Serializable;
import java.util.*;

import com.sorin.idea.dao.*;
import com.sorin.idea.exceptions.*;
import com.sorin.idea.factory.*;

public class ArrEstudioResultado implements Serializable
{
	/** 
	 * This attribute maps to the column IDESTUDIO in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer idestudio;

	/** 
	 * This attribute maps to the column IDABLACION in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer idablacion;

	/** 
	 * This attribute maps to the column IDRES in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer idres = 0;

	/** 
	 * This attribute maps to the column IDPARCIAL in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer idparcial;

	/** 
	 * This attribute maps to the column IDTIN in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer idtin = 0;

	/** 
	 * This attribute maps to the column IDTAM in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer idtam;

	/** 
	 * This attribute maps to the column IDFA in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer idfa;

	/** 
	 * This attribute maps to the column IDIAM in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer idiam;

	/** 
	 * This attribute maps to the column IDNOIAM in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer idnoiam;

	/** 
	 * This attribute maps to the column VAC in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer vac;

	/** 
	 * This attribute maps to the column TAF in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer taf;

	/** 
	 * This attribute maps to the column TVI in the ARR_ESTUDIO_RESULTADO table.
	 */
	protected Integer tvi;

	/**
	 * Method 'ArrEstudioResultado'
	 * 
	 */
	public ArrEstudioResultado()
	{
	}

	/**
	 * Method 'getIdestudio'
	 * 
	 * @return Integer
	 */
	public Integer getIdestudio()
	{
		return idestudio;
	}

	/**
	 * Method 'setIdestudio'
	 * 
	 * @param idestudio
	 */
	public void setIdestudio(Integer idestudio)
	{
		this.idestudio = idestudio;
	}

	/**
	 * Method 'getIdablacion'
	 * 
	 * @return Integer
	 */
	public Integer getIdablacion() {
		return idablacion;
	}

	/**
	 * Method 'setIdablacion'
	 * 
	 * @param idablacion
	 */
	public void setIdablacion(Integer idablacion) {
		this.idablacion = idablacion;
	}

	/**
	 * Method 'getIdres'
	 * 
	 * @return Integer
	 */
	public Integer getIdres()
	{
		return idres;
	}

	/**
	 * Method 'setIdres'
	 * 
	 * @param idres
	 */
	public void setIdres(Integer idres)
	{
		this.idres = idres;
	}

	/**
	 * Method 'getIdparcial'
	 * 
	 * @return Integer
	 */
	public Integer getIdparcial()
	{
		return idparcial;
	}

	/**
	 * Method 'setIdparcial'
	 * 
	 * @param idparcial
	 */
	public void setIdparcial(Integer idparcial)
	{
		this.idparcial = idparcial;
	}

	/**
	 * Method 'getIdtin'
	 * 
	 * @return Integer
	 */
	public Integer getIdtin()
	{
		return idtin;
	}

	/**
	 * Method 'setIdtin'
	 * 
	 * @param idtin
	 */
	public void setIdtin(Integer idtin)
	{
		this.idtin = idtin;
	}

	/**
	 * Method 'getIdtam'
	 * 
	 * @return Integer
	 */
	public Integer getIdtam()
	{
		return idtam;
	}

	/**
	 * Method 'setIdtam'
	 * 
	 * @param idtam
	 */
	public void setIdtam(Integer idtam)
	{
		this.idtam = idtam;
	}

	/**
	 * Method 'getIdfa'
	 * 
	 * @return Integer
	 */
	public Integer getIdfa()
	{
		return idfa;
	}

	/**
	 * Method 'setIdfa'
	 * 
	 * @param idfa
	 */
	public void setIdfa(Integer idfa)
	{
		this.idfa = idfa;
	}

	/**
	 * Method 'getIdiam'
	 * 
	 * @return Integer
	 */
	public Integer getIdiam()
	{
		return idiam;
	}

	/**
	 * Method 'setIdiam'
	 * 
	 * @param idiam
	 */
	public void setIdiam(Integer idiam)
	{
		this.idiam = idiam;
	}

	/**
	 * Method 'getIdnoiam'
	 * 
	 * @return Integer
	 */
	public Integer getIdnoiam()
	{
		return idnoiam;
	}

	/**
	 * Method 'setIdnoiam'
	 * 
	 * @param idnoiam
	 */
	public void setIdnoiam(Integer idnoiam)
	{
		this.idnoiam = idnoiam;
	}

	/**
	 * Method 'getVac'
	 * 
	 * @return Integer
	 */
	public Integer getVac()
	{
		return vac;
	}
	public Boolean getVacb()
	{
		if(vac != null && vac == 1)
			return true;
		return false;
	}

	/**
	 * Method 'setVac'
	 * 
	 * @param vac
	 */
	public void setVac(Integer vac)
	{
		this.vac = vac;
	}
	public void setVacb(Boolean vac)
	{
		if(vac != null && vac)
			this.vac = 1;
		else
			this.vac = 0;
	}

	/**
	 * Method 'getTaf'
	 * 
	 * @return Integer
	 */
	public Integer getTaf()
	{
		return taf;
	}
	public Boolean getTafb()
	{
		if(taf != null && taf == 1)
			return true;
		return false;
	}

	/**
	 * Method 'setTaf'
	 * 
	 * @param taf
	 */
	public void setTaf(Integer taf)
	{
		this.taf = taf;
	}
	public void setTafb(Boolean taf)
	{
		if(taf != null && taf)
			this.taf = 1;
		else
			this.taf = 0;
	}

	/**
	 * Method 'getTvi'
	 * 
	 * @return Integer
	 */
	public Integer getTvi()
	{
		return tvi;
	}
	public Boolean getTvib()
	{
		if(tvi != null && tvi == 1)
			return true;
		return false;
	}

	/**
	 * Method 'setTvi'
	 * 
	 * @param tvi
	 */
	public void setTvi(Integer tvi)
	{
		this.tvi = tvi;
	}
	public void setTvib(Boolean tvi)
	{
		if(tvi != null && tvi)
			this.tvi = 1;
		else
			this.tvi = 0;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ArrEstudioResultado)) {
			return false;
		}
		
		final ArrEstudioResultado _cast = (ArrEstudioResultado) _other;
		if (idestudio == null ? _cast.idestudio != idestudio : !idestudio.equals( _cast.idestudio )) {
			return false;
		}
		
		if (idres == null ? _cast.idres != idres : !idres.equals( _cast.idres )) {
			return false;
		}
		
		if (idparcial == null ? _cast.idparcial != idparcial : !idparcial.equals( _cast.idparcial )) {
			return false;
		}
		
		if (idtin == null ? _cast.idtin != idtin : !idtin.equals( _cast.idtin )) {
			return false;
		}
		
		if (idtam == null ? _cast.idtam != idtam : !idtam.equals( _cast.idtam )) {
			return false;
		}
		
		if (idfa == null ? _cast.idfa != idfa : !idfa.equals( _cast.idfa )) {
			return false;
		}
		
		if (idiam == null ? _cast.idiam != idiam : !idiam.equals( _cast.idiam )) {
			return false;
		}
		
		if (idnoiam == null ? _cast.idnoiam != idnoiam : !idnoiam.equals( _cast.idnoiam )) {
			return false;
		}
		
		if (vac == null ? _cast.vac != vac : !vac.equals( _cast.vac )) {
			return false;
		}
		
		if (taf == null ? _cast.taf != taf : !taf.equals( _cast.taf )) {
			return false;
		}
		
		if (tvi == null ? _cast.tvi != tvi : !tvi.equals( _cast.tvi )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idestudio != null) {
			_hashCode = 29 * _hashCode + idestudio.hashCode();
		}
		
		if (idres != null) {
			_hashCode = 29 * _hashCode + idres.hashCode();
		}
		
		if (idparcial != null) {
			_hashCode = 29 * _hashCode + idparcial.hashCode();
		}
		
		if (idtin != null) {
			_hashCode = 29 * _hashCode + idtin.hashCode();
		}
		
		if (idtam != null) {
			_hashCode = 29 * _hashCode + idtam.hashCode();
		}
		
		if (idfa != null) {
			_hashCode = 29 * _hashCode + idfa.hashCode();
		}
		
		if (idiam != null) {
			_hashCode = 29 * _hashCode + idiam.hashCode();
		}
		
		if (idnoiam != null) {
			_hashCode = 29 * _hashCode + idnoiam.hashCode();
		}
		
		if (vac != null) {
			_hashCode = 29 * _hashCode + vac.hashCode();
		}
		
		if (taf != null) {
			_hashCode = 29 * _hashCode + taf.hashCode();
		}
		
		if (tvi != null) {
			_hashCode = 29 * _hashCode + tvi.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ArrEstudioResultadoPk
	 */
	public ArrEstudioResultadoPk createPk()
	{
		return new ArrEstudioResultadoPk(idestudio, idablacion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "hvn.apl.jProyecto2011.dto.ArrEstudioResultado: " );
		ret.append( "idestudio=" + idestudio );
		ret.append( ", idres=" + idres );
		ret.append( ", idparcial=" + idparcial );
		ret.append( ", idtin=" + idtin );
		ret.append( ", idtam=" + idtam );
		ret.append( ", idfa=" + idfa );
		ret.append( ", idiam=" + idiam );
		ret.append( ", idnoiam=" + idnoiam );
		ret.append( ", vac=" + vac );
		ret.append( ", taf=" + taf );
		ret.append( ", tvi=" + tvi );
		return ret.toString();
	}

}
