/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the med_generico table.
 */
public class MedGenericoPk implements Serializable
{
	protected Integer idmedgen;

	/** 
	 * Sets the value of idmedgen
	 */
	public void setIdmedgen(Integer idmedgen)
	{
		this.idmedgen = idmedgen;
	}

	/** 
	 * Gets the value of idmedgen
	 */
	public Integer getIdmedgen()
	{
		return idmedgen;
	}

	/**
	 * Method 'MedGenericoPk'
	 * 
	 */
	public MedGenericoPk()
	{
	}

	/**
	 * Method 'MedGenericoPk'
	 * 
	 * @param idmedgen
	 */
	public MedGenericoPk(final Integer idmedgen)
	{
		this.idmedgen = idmedgen;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MedGenericoPk)) {
			return false;
		}
		
		final MedGenericoPk _cast = (MedGenericoPk) _other;
		if (idmedgen == null ? _cast.idmedgen != idmedgen : !idmedgen.equals( _cast.idmedgen )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idmedgen != null) {
			_hashCode = 29 * _hashCode + idmedgen.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.sorin.idea.dto.MedGenericoPk: " );
		ret.append( "idmedgen=" + idmedgen );
		return ret.toString();
	}

}
