/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the arr_acceso_priv table.
 */
public class ArrAccesoPrivPk implements Serializable
{
	protected Integer idrol;

	/** 
	 * Sets the value of idrol
	 */
	public void setIdrol(Integer idrol)
	{
		this.idrol = idrol;
	}

	/** 
	 * Gets the value of idrol
	 */
	public Integer getIdrol()
	{
		return idrol;
	}

	/**
	 * Method 'ArrAccesoPrivPk'
	 * 
	 */
	public ArrAccesoPrivPk()
	{
	}

	/**
	 * Method 'ArrAccesoPrivPk'
	 * 
	 * @param idrol
	 */
	public ArrAccesoPrivPk(final Integer idrol)
	{
		this.idrol = idrol;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ArrAccesoPrivPk)) {
			return false;
		}
		
		final ArrAccesoPrivPk _cast = (ArrAccesoPrivPk) _other;
		if (idrol == null ? _cast.idrol != idrol : !idrol.equals( _cast.idrol )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idrol != null) {
			_hashCode = 29 * _hashCode + idrol.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.sorin.idea.dto.ArrAccesoPrivPk: " );
		ret.append( "idrol=" + idrol );
		return ret.toString();
	}

}
