/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the imp_atp table.
 */
public class ImpAtpPk implements Serializable
{
	protected Integer idatp;

	/** 
	 * Sets the value of idatp
	 */
	public void setIdatp(Integer idatp)
	{
		this.idatp = idatp;
	}

	/** 
	 * Gets the value of idatp
	 */
	public Integer getIdatp()
	{
		return idatp;
	}

	/**
	 * Method 'ImpAtpPk'
	 * 
	 */
	public ImpAtpPk()
	{
	}

	/**
	 * Method 'ImpAtpPk'
	 * 
	 * @param idatp
	 */
	public ImpAtpPk(final Integer idatp)
	{
		this.idatp = idatp;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ImpAtpPk)) {
			return false;
		}
		
		final ImpAtpPk _cast = (ImpAtpPk) _other;
		if (idatp == null ? _cast.idatp != idatp : !idatp.equals( _cast.idatp )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idatp != null) {
			_hashCode = 29 * _hashCode + idatp.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "hvn.apl.jProyecto2011.dto.ImpAtpPk: " );
		ret.append( "idatp=" + idatp );
		return ret.toString();
	}

}
