/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import com.sorin.idea.dao.*;
import com.sorin.idea.factory.*;
import com.sorin.idea.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ImpMedIntra implements Serializable
{
	/** 
	 * This attribute maps to the column IDMEDINTRA in the imp_med_intra table.
	 */
	protected Integer idmedintra;

	/** 
	 * This attribute maps to the column IDHOJAIMP in the imp_med_intra table.
	 */
	protected Integer idhojaimp;

	/** 
	 * This attribute maps to the column PROFI_ANTIBIO in the imp_med_intra table.
	 */
	protected Integer profiAntibio;

	/** 
	 * This attribute maps to the column PROFI_ANTIBIO_OTRA in the imp_med_intra table.
	 */
	protected String profiAntibioOtra;

	/** 
	 * This attribute maps to the column ANTICOAG in the imp_med_intra table.
	 */
	protected Integer anticoag;

	/** 
	 * This attribute maps to the column ANTICOAG_OTRA in the imp_med_intra table.
	 */
	protected String anticoagOtra;

	/** 
	 * This attribute maps to the column ANTICOAG_RETIRADA in the imp_med_intra table.
	 */
	protected Integer anticoagRetirada;

	/** 
	 * This attribute maps to the column INR in the imp_med_intra table.
	 */
	protected String inr;

	/** 
	 * This attribute maps to the column OBSERVACIONES in the imp_med_intra table.
	 */
	protected String observaciones;

	/**
	 * Method 'ImpMedIntra'
	 * 
	 */
	public ImpMedIntra()
	{
	}

	/**
	 * Method 'getIdmedintra'
	 * 
	 * @return Integer
	 */
	public Integer getIdmedintra()
	{
		return idmedintra;
	}

	/**
	 * Method 'setIdmedintra'
	 * 
	 * @param idmedintra
	 */
	public void setIdmedintra(Integer idmedintra)
	{
		this.idmedintra = idmedintra;
	}

	/**
	 * Method 'getIdhojaimp'
	 * 
	 * @return Integer
	 */
	public Integer getIdhojaimp()
	{
		return idhojaimp;
	}

	/**
	 * Method 'setIdhojaimp'
	 * 
	 * @param idhojaimp
	 */
	public void setIdhojaimp(Integer idhojaimp)
	{
		this.idhojaimp = idhojaimp;
	}

	/**
	 * Method 'getProfiAntibio'
	 * 
	 * @return Integer
	 */
	public Integer getProfiAntibio()
	{
		return profiAntibio;
	}

	/**
	 * Method 'setProfiAntibio'
	 * 
	 * @param profiAntibio
	 */
	public void setProfiAntibio(Integer profiAntibio)
	{
		this.profiAntibio = profiAntibio;
	}

	/**
	 * Method 'getProfiAntibioOtra'
	 * 
	 * @return String
	 */
	public String getProfiAntibioOtra()
	{
		return profiAntibioOtra;
	}

	/**
	 * Method 'setProfiAntibioOtra'
	 * 
	 * @param profiAntibioOtra
	 */
	public void setProfiAntibioOtra(String profiAntibioOtra)
	{
		this.profiAntibioOtra = profiAntibioOtra;
	}

	/**
	 * Method 'getAnticoag'
	 * 
	 * @return Integer
	 */
	public Integer getAnticoag()
	{
		return anticoag;
	}

	/**
	 * Method 'setAnticoag'
	 * 
	 * @param anticoag
	 */
	public void setAnticoag(Integer anticoag)
	{
		this.anticoag = anticoag;
	}

	/**
	 * Method 'getAnticoagOtra'
	 * 
	 * @return String
	 */
	public String getAnticoagOtra()
	{
		return anticoagOtra;
	}

	/**
	 * Method 'setAnticoagOtra'
	 * 
	 * @param anticoagOtra
	 */
	public void setAnticoagOtra(String anticoagOtra)
	{
		this.anticoagOtra = anticoagOtra;
	}

	/**
	 * Method 'getAnticoagRetirada'
	 * 
	 * @return Integer
	 */
	public Integer getAnticoagRetirada()
	{
		return anticoagRetirada;
	}

	/**
	 * Method 'setAnticoagRetirada'
	 * 
	 * @param anticoagRetirada
	 */
	public void setAnticoagRetirada(Integer anticoagRetirada)
	{
		this.anticoagRetirada = anticoagRetirada;
	}

	/**
	 * Method 'getInr'
	 * 
	 * @return String
	 */
	public String getInr()
	{
		return inr;
	}

	/**
	 * Method 'setInr'
	 * 
	 * @param inr
	 */
	public void setInr(String inr)
	{
		this.inr = inr;
	}

	/**
	 * Method 'getObservaciones'
	 * 
	 * @return String
	 */
	public String getObservaciones()
	{
		return observaciones;
	}

	/**
	 * Method 'setObservaciones'
	 * 
	 * @param observaciones
	 */
	public void setObservaciones(String observaciones)
	{
		this.observaciones = observaciones;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ImpMedIntra)) {
			return false;
		}
		
		final ImpMedIntra _cast = (ImpMedIntra) _other;
		if (idmedintra == null ? _cast.idmedintra != idmedintra : !idmedintra.equals( _cast.idmedintra )) {
			return false;
		}
		
		if (idhojaimp == null ? _cast.idhojaimp != idhojaimp : !idhojaimp.equals( _cast.idhojaimp )) {
			return false;
		}
		
		if (profiAntibio == null ? _cast.profiAntibio != profiAntibio : !profiAntibio.equals( _cast.profiAntibio )) {
			return false;
		}
		
		if (profiAntibioOtra == null ? _cast.profiAntibioOtra != profiAntibioOtra : !profiAntibioOtra.equals( _cast.profiAntibioOtra )) {
			return false;
		}
		
		if (anticoag == null ? _cast.anticoag != anticoag : !anticoag.equals( _cast.anticoag )) {
			return false;
		}
		
		if (anticoagOtra == null ? _cast.anticoagOtra != anticoagOtra : !anticoagOtra.equals( _cast.anticoagOtra )) {
			return false;
		}
		
		if (anticoagRetirada == null ? _cast.anticoagRetirada != anticoagRetirada : !anticoagRetirada.equals( _cast.anticoagRetirada )) {
			return false;
		}
		
		if (inr == null ? _cast.inr != inr : !inr.equals( _cast.inr )) {
			return false;
		}
		
		if (observaciones == null ? _cast.observaciones != observaciones : !observaciones.equals( _cast.observaciones )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idmedintra != null) {
			_hashCode = 29 * _hashCode + idmedintra.hashCode();
		}
		
		if (idhojaimp != null) {
			_hashCode = 29 * _hashCode + idhojaimp.hashCode();
		}
		
		if (profiAntibio != null) {
			_hashCode = 29 * _hashCode + profiAntibio.hashCode();
		}
		
		if (profiAntibioOtra != null) {
			_hashCode = 29 * _hashCode + profiAntibioOtra.hashCode();
		}
		
		if (anticoag != null) {
			_hashCode = 29 * _hashCode + anticoag.hashCode();
		}
		
		if (anticoagOtra != null) {
			_hashCode = 29 * _hashCode + anticoagOtra.hashCode();
		}
		
		if (anticoagRetirada != null) {
			_hashCode = 29 * _hashCode + anticoagRetirada.hashCode();
		}
		
		if (inr != null) {
			_hashCode = 29 * _hashCode + inr.hashCode();
		}
		
		if (observaciones != null) {
			_hashCode = 29 * _hashCode + observaciones.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ImpMedIntraPk
	 */
	public ImpMedIntraPk createPk()
	{
		return new ImpMedIntraPk(idmedintra);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.sorin.idea.dto.ImpMedIntra: " );
		ret.append( "idmedintra=" + idmedintra );
		ret.append( ", idhojaimp=" + idhojaimp );
		ret.append( ", profiAntibio=" + profiAntibio );
		ret.append( ", profiAntibioOtra=" + profiAntibioOtra );
		ret.append( ", anticoag=" + anticoag );
		ret.append( ", anticoagOtra=" + anticoagOtra );
		ret.append( ", anticoagRetirada=" + anticoagRetirada );
		ret.append( ", inr=" + inr );
		ret.append( ", observaciones=" + observaciones );
		return ret.toString();
	}

}
