/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import com.sorin.idea.dao.*;
import com.sorin.idea.factory.*;
import com.sorin.idea.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Complicaciones implements Serializable
{
	/** 
	 * This attribute maps to the column IDCOMPLICACION in the complicaciones table.
	 */
	protected Integer idcomplicacion;

	/** 
	 * This attribute maps to the column NOMBRE in the complicaciones table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column AMBITO in the complicaciones table.
	 */
	protected Integer ambito;

	/**
	 * Method 'Complicaciones'
	 * 
	 */
	public Complicaciones()
	{
	}

	/**
	 * Method 'getIdcomplicacion'
	 * 
	 * @return Integer
	 */
	public Integer getIdcomplicacion()
	{
		return idcomplicacion;
	}

	/**
	 * Method 'setIdcomplicacion'
	 * 
	 * @param idcomplicacion
	 */
	public void setIdcomplicacion(Integer idcomplicacion)
	{
		this.idcomplicacion = idcomplicacion;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getAmbito'
	 * 
	 * @return Integer
	 */
	public Integer getAmbito()
	{
		return ambito;
	}

	/**
	 * Method 'setAmbito'
	 * 
	 * @param ambito
	 */
	public void setAmbito(Integer ambito)
	{
		this.ambito = ambito;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Complicaciones)) {
			return false;
		}
		
		final Complicaciones _cast = (Complicaciones) _other;
		if (idcomplicacion == null ? _cast.idcomplicacion != idcomplicacion : !idcomplicacion.equals( _cast.idcomplicacion )) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (ambito == null ? _cast.ambito != ambito : !ambito.equals( _cast.ambito )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idcomplicacion != null) {
			_hashCode = 29 * _hashCode + idcomplicacion.hashCode();
		}
		
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		if (ambito != null) {
			_hashCode = 29 * _hashCode + ambito.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ComplicacionesPk
	 */
	public ComplicacionesPk createPk()
	{
		return new ComplicacionesPk(idcomplicacion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.sorin.idea.dto.Complicaciones: " );
		ret.append( "idcomplicacion=" + idcomplicacion );
		ret.append( ", nombre=" + nombre );
		ret.append( ", ambito=" + ambito );
		return ret.toString();
	}

}
