/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import com.sorin.idea.dao.*;
import com.sorin.idea.factory.*;
import com.sorin.idea.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Evento implements Serializable
{
	/** 
	 * This attribute maps to the column IDEVENTO in the evento table.
	 */
	protected Integer idevento;

	/** 
	 * This attribute maps to the column CODIGO in the evento table.
	 */
	protected Integer codigo;

	/** 
	 * This attribute maps to the column IDUSUARIO in the evento table.
	 */
	protected String idusuario;

	/** 
	 * This attribute maps to the column PROCEDIMIENTO in the evento table.
	 */
	protected Integer procedimiento;

	/** 
	 * This attribute maps to the column DESCRIPCION in the evento table.
	 */
	protected String descripcion;

	/** 
	 * This attribute maps to the column SOLICITANTE in the evento table.
	 */
	protected String solicitante;

	/** 
	 * This attribute maps to the column FECHAINI in the evento table.
	 */
	protected Date fechaini;

	/** 
	 * This attribute maps to the column FECHAFIN in the evento table.
	 */
	protected Date fechafin;

	/** 
	 * This attribute maps to the column IDENTIFICADOR in the evento table.
	 */
	protected String identificador;

	/** 
	 * This attribute maps to the column ESTADO in the evento table.
	 */
	protected Integer estado;

	/** 
	 * This attribute maps to the column RESPONSABLE in the evento table.
	 */
	protected String responsable;

	/** 
	 * This attribute maps to the column IDPACIENTE in the evento table.
	 */
	protected String idpaciente;

	/** 
	 * This attribute maps to the column FECHAASIGNACION in the evento table.
	 */
	protected Date fechaasignacion;

	/** 
	 * This attribute maps to the column NOMBRE in the evento table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column APELLIDO1 in the evento table.
	 */
	protected String apellido1;

	/** 
	 * This attribute maps to the column APELLIDO2 in the evento table.
	 */
	protected String apellido2;

	/** 
	 * This attribute maps to the column FNAC in the evento table.
	 */
	protected Date fnac;

	/** 
	 * This attribute maps to the column TIPO in the evento table.
	 */
	protected Integer tipo;

	private Integer duracion;
	private boolean tododia;
	protected String hora_ini;
	protected String min_ini;
	protected Integer huecos;
	protected Integer tipogen;
	private String huecoselected;
	
	/**
	 * Method 'Evento'
	 * 
	 */
	public Evento()
	{
		this.tipogen = 0;
	}

	/**
	 * Method 'getIdevento'
	 * 
	 * @return Integer
	 */
	public Integer getIdevento()
	{
		return idevento;
	}

	/**
	 * Method 'setIdevento'
	 * 
	 * @param idevento
	 */
	public void setIdevento(Integer idevento)
	{
		this.idevento = idevento;
	}

	/**
	 * Method 'getCodigo'
	 * 
	 * @return Integer
	 */
	public Integer getCodigo()
	{
		return codigo;
	}

	/**
	 * Method 'setCodigo'
	 * 
	 * @param codigo
	 */
	public void setCodigo(Integer codigo)
	{
		this.codigo = codigo;
	}

	/**
	 * Method 'getIdusuario'
	 * 
	 * @return String
	 */
	public String getIdusuario()
	{
		return idusuario;
	}

	/**
	 * Method 'setIdusuario'
	 * 
	 * @param idusuario
	 */
	public void setIdusuario(String idusuario)
	{
		this.idusuario = idusuario;
	}

	/**
	 * Method 'getProcedimiento'
	 * 
	 * @return Integer
	 */
	public Integer getProcedimiento()
	{
		return procedimiento;
	}

	/**
	 * Method 'setProcedimiento'
	 * 
	 * @param procedimiento
	 */
	public void setProcedimiento(Integer procedimiento)
	{
		this.procedimiento = procedimiento;
	}

	/**
	 * Method 'getDescripcion'
	 * 
	 * @return String
	 */
	public String getDescripcion()
	{
		return descripcion;
	}

	/**
	 * Method 'setDescripcion'
	 * 
	 * @param descripcion
	 */
	public void setDescripcion(String descripcion)
	{
		this.descripcion = descripcion;
	}

	/**
	 * Method 'getSolicitante'
	 * 
	 * @return String
	 */
	public String getSolicitante()
	{
		return solicitante;
	}

	/**
	 * Method 'setSolicitante'
	 * 
	 * @param solicitante
	 */
	public void setSolicitante(String solicitante)
	{
		this.solicitante = solicitante;
	}

	/**
	 * Method 'getFechaini'
	 * 
	 * @return Date
	 */
	public Date getFechaini()
	{
		return fechaini;
	}

	/**
	 * Method 'setFechaini'
	 * 
	 * @param fechaini
	 */
	public void setFechaini(Date fechaini)
	{
		this.fechaini = fechaini;
	}

	/**
	 * Method 'getFechafin'
	 * 
	 * @return Date
	 */
	public Date getFechafin()
	{
		return fechafin;
	}

	/**
	 * Method 'setFechafin'
	 * 
	 * @param fechafin
	 */
	public void setFechafin(Date fechafin)
	{
		this.fechafin = fechafin;
	}

	/**
	 * Method 'getIdentificador'
	 * 
	 * @return String
	 */
	public String getIdentificador()
	{
		return identificador;
	}

	/**
	 * Method 'setIdentificador'
	 * 
	 * @param identificador
	 */
	public void setIdentificador(String identificador)
	{
		this.identificador = identificador;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return Integer
	 */
	public Integer getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(Integer estado)
	{
		this.estado = estado;
	}

	/**
	 * Method 'getResponsable'
	 * 
	 * @return String
	 */
	public String getResponsable()
	{
		return responsable;
	}

	/**
	 * Method 'setResponsable'
	 * 
	 * @param responsable
	 */
	public void setResponsable(String responsable)
	{
		this.responsable = responsable;
	}

	/**
	 * Method 'getIdpaciente'
	 * 
	 * @return String
	 */
	public String getIdpaciente()
	{
		return idpaciente;
	}

	/**
	 * Method 'setIdpaciente'
	 * 
	 * @param idpaciente
	 */
	public void setIdpaciente(String idpaciente)
	{
		this.idpaciente = idpaciente;
	}

	/**
	 * Method 'getFechaasignacion'
	 * 
	 * @return Date
	 */
	public Date getFechaasignacion()
	{
		return fechaasignacion;
	}

	/**
	 * Method 'setFechaasignacion'
	 * 
	 * @param fechaasignacion
	 */
	public void setFechaasignacion(Date fechaasignacion)
	{
		this.fechaasignacion = fechaasignacion;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getApellido1'
	 * 
	 * @return String
	 */
	public String getApellido1()
	{
		return apellido1;
	}

	/**
	 * Method 'setApellido1'
	 * 
	 * @param apellido1
	 */
	public void setApellido1(String apellido1)
	{
		this.apellido1 = apellido1;
	}

	/**
	 * Method 'getApellido2'
	 * 
	 * @return String
	 */
	public String getApellido2()
	{
		return apellido2;
	}

	/**
	 * Method 'setApellido2'
	 * 
	 * @param apellido2
	 */
	public void setApellido2(String apellido2)
	{
		this.apellido2 = apellido2;
	}

	/**
	 * Method 'getFnac'
	 * 
	 * @return Date
	 */
	public Date getFnac()
	{
		return fnac;
	}

	/**
	 * Method 'setFnac'
	 * 
	 * @param fnac
	 */
	public void setFnac(Date fnac)
	{
		this.fnac = fnac;
	}

	/**
	 * Method 'getTipo'
	 * 
	 * @return Integer
	 */
	public Integer getTipo()
	{
		return tipo;
	}

	/**
	 * Method 'setTipo'
	 * 
	 * @param tipo
	 */
	public void setTipo(Integer tipo)
	{
		this.tipo = tipo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Evento)) {
			return false;
		}
		
		final Evento _cast = (Evento) _other;
		if (idevento == null ? _cast.idevento != idevento : !idevento.equals( _cast.idevento )) {
			return false;
		}
		
		if (codigo == null ? _cast.codigo != codigo : !codigo.equals( _cast.codigo )) {
			return false;
		}
		
		if (idusuario == null ? _cast.idusuario != idusuario : !idusuario.equals( _cast.idusuario )) {
			return false;
		}
		
		if (procedimiento == null ? _cast.procedimiento != procedimiento : !procedimiento.equals( _cast.procedimiento )) {
			return false;
		}
		
		if (descripcion == null ? _cast.descripcion != descripcion : !descripcion.equals( _cast.descripcion )) {
			return false;
		}
		
		if (solicitante == null ? _cast.solicitante != solicitante : !solicitante.equals( _cast.solicitante )) {
			return false;
		}
		
		if (fechaini == null ? _cast.fechaini != fechaini : !fechaini.equals( _cast.fechaini )) {
			return false;
		}
		
		if (fechafin == null ? _cast.fechafin != fechafin : !fechafin.equals( _cast.fechafin )) {
			return false;
		}
		
		if (identificador == null ? _cast.identificador != identificador : !identificador.equals( _cast.identificador )) {
			return false;
		}
		
		if (estado == null ? _cast.estado != estado : !estado.equals( _cast.estado )) {
			return false;
		}
		
		if (responsable == null ? _cast.responsable != responsable : !responsable.equals( _cast.responsable )) {
			return false;
		}
		
		if (idpaciente == null ? _cast.idpaciente != idpaciente : !idpaciente.equals( _cast.idpaciente )) {
			return false;
		}
		
		if (fechaasignacion == null ? _cast.fechaasignacion != fechaasignacion : !fechaasignacion.equals( _cast.fechaasignacion )) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (apellido1 == null ? _cast.apellido1 != apellido1 : !apellido1.equals( _cast.apellido1 )) {
			return false;
		}
		
		if (apellido2 == null ? _cast.apellido2 != apellido2 : !apellido2.equals( _cast.apellido2 )) {
			return false;
		}
		
		if (fnac == null ? _cast.fnac != fnac : !fnac.equals( _cast.fnac )) {
			return false;
		}
		
		if (tipo == null ? _cast.tipo != tipo : !tipo.equals( _cast.tipo )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idevento != null) {
			_hashCode = 29 * _hashCode + idevento.hashCode();
		}
		
		if (codigo != null) {
			_hashCode = 29 * _hashCode + codigo.hashCode();
		}
		
		if (idusuario != null) {
			_hashCode = 29 * _hashCode + idusuario.hashCode();
		}
		
		if (procedimiento != null) {
			_hashCode = 29 * _hashCode + procedimiento.hashCode();
		}
		
		if (descripcion != null) {
			_hashCode = 29 * _hashCode + descripcion.hashCode();
		}
		
		if (solicitante != null) {
			_hashCode = 29 * _hashCode + solicitante.hashCode();
		}
		
		if (fechaini != null) {
			_hashCode = 29 * _hashCode + fechaini.hashCode();
		}
		
		if (fechafin != null) {
			_hashCode = 29 * _hashCode + fechafin.hashCode();
		}
		
		if (identificador != null) {
			_hashCode = 29 * _hashCode + identificador.hashCode();
		}
		
		if (estado != null) {
			_hashCode = 29 * _hashCode + estado.hashCode();
		}
		
		if (responsable != null) {
			_hashCode = 29 * _hashCode + responsable.hashCode();
		}
		
		if (idpaciente != null) {
			_hashCode = 29 * _hashCode + idpaciente.hashCode();
		}
		
		if (fechaasignacion != null) {
			_hashCode = 29 * _hashCode + fechaasignacion.hashCode();
		}
		
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		if (apellido1 != null) {
			_hashCode = 29 * _hashCode + apellido1.hashCode();
		}
		
		if (apellido2 != null) {
			_hashCode = 29 * _hashCode + apellido2.hashCode();
		}
		
		if (fnac != null) {
			_hashCode = 29 * _hashCode + fnac.hashCode();
		}
		
		if (tipo != null) {
			_hashCode = 29 * _hashCode + tipo.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EventoPk
	 */
	public EventoPk createPk()
	{
		return new EventoPk(idevento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.sorin.idea.dto.Evento: " );
		ret.append( "idevento=" + idevento );
		ret.append( ", codigo=" + codigo );
		ret.append( ", idusuario=" + idusuario );
		ret.append( ", procedimiento=" + procedimiento );
		ret.append( ", descripcion=" + descripcion );
		ret.append( ", solicitante=" + solicitante );
		ret.append( ", fechaini=" + fechaini );
		ret.append( ", fechafin=" + fechafin );
		ret.append( ", identificador=" + identificador );
		ret.append( ", estado=" + estado );
		ret.append( ", responsable=" + responsable );
		ret.append( ", idpaciente=" + idpaciente );
		ret.append( ", fechaasignacion=" + fechaasignacion );
		ret.append( ", nombre=" + nombre );
		ret.append( ", apellido1=" + apellido1 );
		ret.append( ", apellido2=" + apellido2 );
		ret.append( ", fnac=" + fnac );
		ret.append( ", tipo=" + tipo );
		return ret.toString();
	}

	public Integer getDuracion() {
		return duracion;
	}

	public void setDuracion(Integer duracion) {
		this.duracion = duracion;
	}

	public boolean isTododia() {
		return tododia;
	}

	public void setTododia(boolean tododia) {
		this.tododia = tododia;
	}

	public String getHora_ini() {
		return hora_ini;
	}

	public void setHora_ini(String hora_ini) {
		this.hora_ini = hora_ini;
	}

	public String getMin_ini() {
		return min_ini;
	}

	public void setMin_ini(String min_ini) {
		this.min_ini = min_ini;
	}

	public Integer getHuecos() {
		return huecos;
	}

	public void setHuecos(Integer huecos) {
		this.huecos = huecos;
	}

	public Integer getTipogen() {
		return tipogen;
	}

	public void setTipogen(Integer tipogen) {
		this.tipogen = tipogen;
	}

	public String getHuecoselected() {
		return huecoselected;
	}

	public void setHuecoselected(String huecoselected) {
		this.huecoselected = huecoselected;
	}

}
