/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the episodio table.
 */
public class EpisodioPk implements Serializable
{
	protected Integer idepisodio;

	/** 
	 * Sets the value of idepisodio
	 */
	public void setIdepisodio(Integer idepisodio)
	{
		this.idepisodio = idepisodio;
	}

	/** 
	 * Gets the value of idepisodio
	 */
	public Integer getIdepisodio()
	{
		return idepisodio;
	}

	/**
	 * Method 'EpisodioPk'
	 * 
	 */
	public EpisodioPk()
	{
	}

	/**
	 * Method 'EpisodioPk'
	 * 
	 * @param idepisodio
	 */
	public EpisodioPk(final Integer idepisodio)
	{
		this.idepisodio = idepisodio;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EpisodioPk)) {
			return false;
		}
		
		final EpisodioPk _cast = (EpisodioPk) _other;
		if (idepisodio == null ? _cast.idepisodio != idepisodio : !idepisodio.equals( _cast.idepisodio )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idepisodio != null) {
			_hashCode = 29 * _hashCode + idepisodio.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.sorin.idea.dto.EpisodioPk: " );
		ret.append( "idepisodio=" + idepisodio );
		return ret.toString();
	}

}
