/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import java.io.Serializable;
import java.util.*;

import com.sorin.idea.dao.*;
import com.sorin.idea.exceptions.*;
import com.sorin.idea.factory.*;

public class ArrAnualSubstratos implements Serializable
{
	/** 
	 * This attribute maps to the column ANIO in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected Integer anio;

	/** 
	 * This attribute maps to the column SUBSTRATO in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected Integer substrato;

	/** 
	 * This attribute maps to the column CAMPO1 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo1;

	/** 
	 * This attribute maps to the column CAMPO2 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo2;

	/** 
	 * This attribute maps to the column CAMPO3 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo3;

	/** 
	 * This attribute maps to the column CAMPO4 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo4;

	/** 
	 * This attribute maps to the column CAMPO5 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo5;

	/** 
	 * This attribute maps to the column CAMPO6 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo6;

	/** 
	 * This attribute maps to the column CAMPO7 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo7;

	/** 
	 * This attribute maps to the column CAMPO8 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo8;

	/** 
	 * This attribute maps to the column CAMPO9 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo9;

	/** 
	 * This attribute maps to the column CAMPO10 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo10;

	/** 
	 * This attribute maps to the column CAMPO11 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo11;

	/** 
	 * This attribute maps to the column CAMPO12 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo12;

	/** 
	 * This attribute maps to the column CAMPO13 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo13;

	/** 
	 * This attribute maps to the column CAMPO14 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo14;

	/** 
	 * This attribute maps to the column CAMPO15 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo15;

	/** 
	 * This attribute maps to the column CAMPO16 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo16;

	/** 
	 * This attribute maps to the column CAMPO17 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo17;

	/** 
	 * This attribute maps to the column CAMPO18 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo18;

	/** 
	 * This attribute maps to the column CAMPO19 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo19;

	/** 
	 * This attribute maps to the column CAMPO20 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo20;

	/** 
	 * This attribute maps to the column CAMPO21 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo21;

	/** 
	 * This attribute maps to the column CAMPO22 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo22;

	/** 
	 * This attribute maps to the column CAMPO23 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo23;

	/** 
	 * This attribute maps to the column CAMPO24 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo24;

	/** 
	 * This attribute maps to the column CAMPO25 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo25;

	/** 
	 * This attribute maps to the column CAMPO26 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo26;

	/** 
	 * This attribute maps to the column CAMPO27 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo27;

	/** 
	 * This attribute maps to the column CAMPO28 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo28;

	/** 
	 * This attribute maps to the column CAMPO29 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo29;

	/** 
	 * This attribute maps to the column CAMPO30 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo30;

	/** 
	 * This attribute maps to the column CAMPO31 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo31;

	/** 
	 * This attribute maps to the column CAMPO32 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo32;

	/** 
	 * This attribute maps to the column CAMPO33 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo33;

	/** 
	 * This attribute maps to the column CAMPO34 in the ARR_ANUAL_SUBSTRATOS table.
	 */
	protected String campo34;

	/** 
	 * This attribute maps to the column CAMPO35 in the arr_anual_substratos table.
	 */
	protected String campo35;

	/** 
	 * This attribute maps to the column CAMPO36 in the arr_anual_substratos table.
	 */
	protected String campo36;

	/** 
	 * This attribute maps to the column CAMPO37 in the arr_anual_substratos table.
	 */
	protected String campo37;

	/** 
	 * This attribute maps to the column CAMPO38 in the arr_anual_substratos table.
	 */
	protected String campo38;

	/** 
	 * This attribute maps to the column CAMPO39 in the arr_anual_substratos table.
	 */
	protected String campo39;

	/** 
	 * This attribute maps to the column CAMPO40 in the arr_anual_substratos table.
	 */
	protected String campo40;

	/** 
	 * This attribute maps to the column CAMPO41 in the arr_anual_substratos table.
	 */
	protected String campo41;

	/** 
	 * This attribute maps to the column CAMPO42 in the arr_anual_substratos table.
	 */
	protected String campo42;

	/** 
	 * This attribute maps to the column CAMPO43 in the arr_anual_substratos table.
	 */
	protected String campo43;

	/** 
	 * This attribute maps to the column CAMPO44 in the arr_anual_substratos table.
	 */
	protected String campo44;

	/** 
	 * This attribute maps to the column CAMPO45 in the arr_anual_substratos table.
	 */
	protected String campo45;

	/** 
	 * This attribute maps to the column CAMPO46 in the arr_anual_substratos table.
	 */
	protected String campo46;

	/** 
	 * This attribute maps to the column CAMPO47 in the arr_anual_substratos table.
	 */
	protected String campo47;

	/** 
	 * This attribute maps to the column CAMPO48 in the arr_anual_substratos table.
	 */
	protected String campo48;

	/** 
	 * This attribute maps to the column CAMPO49 in the arr_anual_substratos table.
	 */
	protected String campo49;

	/** 
	 * This attribute maps to the column CAMPO50 in the arr_anual_substratos table.
	 */
	protected String campo50;
	
	private String catRFFasica;
	private String catRFIrrig;
	private String catLaser;
	
	/**
	 * Method 'ArrAnualSubstratos'
	 * 
	 */
	public ArrAnualSubstratos(Integer anio, Integer substrato)
	{
		this.anio = anio;
		this.substrato = substrato;
	}
	public ArrAnualSubstratos()
	{
	}

	/**
	 * Method 'getAnio'
	 * 
	 * @return Integer
	 */
	public Integer getAnio()
	{
		return anio;
	}

	/**
	 * Method 'setAnio'
	 * 
	 * @param anio
	 */
	public void setAnio(Integer anio)
	{
		this.anio = anio;
	}

	/**
	 * Method 'getSubstrato'
	 * 
	 * @return Integer
	 */
	public Integer getSubstrato()
	{
		return substrato;
	}

	/**
	 * Method 'setSubstrato'
	 * 
	 * @param substrato
	 */
	public void setSubstrato(Integer substrato)
	{
		this.substrato = substrato;
	}

	/**
	 * Method 'getCampo1'
	 * 
	 * @return String
	 */
	public String getCampo1()
	{
		return campo1;
	}

	/**
	 * Method 'setCampo1'
	 * 
	 * @param campo1
	 */
	public void setCampo1(String campo1)
	{
		this.campo1 = campo1;
	}

	/**
	 * Method 'getCampo2'
	 * 
	 * @return String
	 */
	public String getCampo2()
	{
		return campo2;
	}

	/**
	 * Method 'setCampo2'
	 * 
	 * @param campo2
	 */
	public void setCampo2(String campo2)
	{
		this.campo2 = campo2;
	}

	/**
	 * Method 'getCampo3'
	 * 
	 * @return String
	 */
	public String getCampo3()
	{
		return campo3;
	}

	/**
	 * Method 'setCampo3'
	 * 
	 * @param campo3
	 */
	public void setCampo3(String campo3)
	{
		this.campo3 = campo3;
	}

	/**
	 * Method 'getCampo4'
	 * 
	 * @return String
	 */
	public String getCampo4()
	{
		return campo4;
	}

	/**
	 * Method 'setCampo4'
	 * 
	 * @param campo4
	 */
	public void setCampo4(String campo4)
	{
		this.campo4 = campo4;
	}

	/**
	 * Method 'getCampo5'
	 * 
	 * @return String
	 */
	public String getCampo5()
	{
		return campo5;
	}

	/**
	 * Method 'setCampo5'
	 * 
	 * @param campo5
	 */
	public void setCampo5(String campo5)
	{
		this.campo5 = campo5;
	}

	/**
	 * Method 'getCampo6'
	 * 
	 * @return String
	 */
	public String getCampo6()
	{
		return campo6;
	}

	/**
	 * Method 'setCampo6'
	 * 
	 * @param campo6
	 */
	public void setCampo6(String campo6)
	{
		this.campo6 = campo6;
	}

	/**
	 * Method 'getCampo7'
	 * 
	 * @return String
	 */
	public String getCampo7()
	{
		return campo7;
	}

	/**
	 * Method 'setCampo7'
	 * 
	 * @param campo7
	 */
	public void setCampo7(String campo7)
	{
		this.campo7 = campo7;
	}

	/**
	 * Method 'getCampo8'
	 * 
	 * @return String
	 */
	public String getCampo8()
	{
		return campo8;
	}

	/**
	 * Method 'setCampo8'
	 * 
	 * @param campo8
	 */
	public void setCampo8(String campo8)
	{
		this.campo8 = campo8;
	}

	/**
	 * Method 'getCampo9'
	 * 
	 * @return String
	 */
	public String getCampo9()
	{
		return campo9;
	}

	/**
	 * Method 'setCampo9'
	 * 
	 * @param campo9
	 */
	public void setCampo9(String campo9)
	{
		this.campo9 = campo9;
	}

	/**
	 * Method 'getCampo10'
	 * 
	 * @return String
	 */
	public String getCampo10()
	{
		return campo10;
	}

	/**
	 * Method 'setCampo10'
	 * 
	 * @param campo10
	 */
	public void setCampo10(String campo10)
	{
		this.campo10 = campo10;
	}

	/**
	 * Method 'getCampo11'
	 * 
	 * @return String
	 */
	public String getCampo11()
	{
		return campo11;
	}

	/**
	 * Method 'setCampo11'
	 * 
	 * @param campo11
	 */
	public void setCampo11(String campo11)
	{
		this.campo11 = campo11;
	}

	/**
	 * Method 'getCampo12'
	 * 
	 * @return String
	 */
	public String getCampo12()
	{
		return campo12;
	}

	/**
	 * Method 'setCampo12'
	 * 
	 * @param campo12
	 */
	public void setCampo12(String campo12)
	{
		this.campo12 = campo12;
	}

	/**
	 * Method 'getCampo13'
	 * 
	 * @return String
	 */
	public String getCampo13()
	{
		return campo13;
	}

	/**
	 * Method 'setCampo13'
	 * 
	 * @param campo13
	 */
	public void setCampo13(String campo13)
	{
		this.campo13 = campo13;
	}

	/**
	 * Method 'getCampo14'
	 * 
	 * @return String
	 */
	public String getCampo14()
	{
		return campo14;
	}

	/**
	 * Method 'setCampo14'
	 * 
	 * @param campo14
	 */
	public void setCampo14(String campo14)
	{
		this.campo14 = campo14;
	}

	/**
	 * Method 'getCampo15'
	 * 
	 * @return String
	 */
	public String getCampo15()
	{
		return campo15;
	}

	/**
	 * Method 'setCampo15'
	 * 
	 * @param campo15
	 */
	public void setCampo15(String campo15)
	{
		this.campo15 = campo15;
	}

	/**
	 * Method 'getCampo16'
	 * 
	 * @return String
	 */
	public String getCampo16()
	{
		return campo16;
	}

	/**
	 * Method 'setCampo16'
	 * 
	 * @param campo16
	 */
	public void setCampo16(String campo16)
	{
		this.campo16 = campo16;
	}

	/**
	 * Method 'getCampo17'
	 * 
	 * @return String
	 */
	public String getCampo17()
	{
		return campo17;
	}

	/**
	 * Method 'setCampo17'
	 * 
	 * @param campo17
	 */
	public void setCampo17(String campo17)
	{
		this.campo17 = campo17;
	}

	/**
	 * Method 'getCampo18'
	 * 
	 * @return String
	 */
	public String getCampo18()
	{
		return campo18;
	}

	/**
	 * Method 'setCampo18'
	 * 
	 * @param campo18
	 */
	public void setCampo18(String campo18)
	{
		this.campo18 = campo18;
	}

	/**
	 * Method 'getCampo19'
	 * 
	 * @return String
	 */
	public String getCampo19()
	{
		return campo19;
	}

	/**
	 * Method 'setCampo19'
	 * 
	 * @param campo19
	 */
	public void setCampo19(String campo19)
	{
		this.campo19 = campo19;
	}

	/**
	 * Method 'getCampo20'
	 * 
	 * @return String
	 */
	public String getCampo20()
	{
		return campo20;
	}

	/**
	 * Method 'setCampo20'
	 * 
	 * @param campo20
	 */
	public void setCampo20(String campo20)
	{
		this.campo20 = campo20;
	}

	/**
	 * Method 'getCampo21'
	 * 
	 * @return String
	 */
	public String getCampo21()
	{
		return campo21;
	}

	/**
	 * Method 'setCampo21'
	 * 
	 * @param campo21
	 */
	public void setCampo21(String campo21)
	{
		this.campo21 = campo21;
	}

	/**
	 * Method 'getCampo22'
	 * 
	 * @return String
	 */
	public String getCampo22()
	{
		return campo22;
	}

	/**
	 * Method 'setCampo22'
	 * 
	 * @param campo22
	 */
	public void setCampo22(String campo22)
	{
		this.campo22 = campo22;
	}

	/**
	 * Method 'getCampo23'
	 * 
	 * @return String
	 */
	public String getCampo23()
	{
		return campo23;
	}

	/**
	 * Method 'setCampo23'
	 * 
	 * @param campo23
	 */
	public void setCampo23(String campo23)
	{
		this.campo23 = campo23;
	}

	/**
	 * Method 'getCampo24'
	 * 
	 * @return String
	 */
	public String getCampo24()
	{
		return campo24;
	}

	/**
	 * Method 'setCampo24'
	 * 
	 * @param campo24
	 */
	public void setCampo24(String campo24)
	{
		this.campo24 = campo24;
	}

	/**
	 * Method 'getCampo25'
	 * 
	 * @return String
	 */
	public String getCampo25()
	{
		return campo25;
	}

	/**
	 * Method 'setCampo25'
	 * 
	 * @param campo25
	 */
	public void setCampo25(String campo25)
	{
		this.campo25 = campo25;
	}

	/**
	 * Method 'getCampo26'
	 * 
	 * @return String
	 */
	public String getCampo26()
	{
		return campo26;
	}

	/**
	 * Method 'setCampo26'
	 * 
	 * @param campo26
	 */
	public void setCampo26(String campo26)
	{
		this.campo26 = campo26;
	}

	/**
	 * Method 'getCampo27'
	 * 
	 * @return String
	 */
	public String getCampo27()
	{
		return campo27;
	}

	/**
	 * Method 'setCampo27'
	 * 
	 * @param campo27
	 */
	public void setCampo27(String campo27)
	{
		this.campo27 = campo27;
	}

	/**
	 * Method 'getCampo28'
	 * 
	 * @return String
	 */
	public String getCampo28()
	{
		return campo28;
	}

	/**
	 * Method 'setCampo28'
	 * 
	 * @param campo28
	 */
	public void setCampo28(String campo28)
	{
		this.campo28 = campo28;
	}

	/**
	 * Method 'getCampo29'
	 * 
	 * @return String
	 */
	public String getCampo29()
	{
		return campo29;
	}

	/**
	 * Method 'setCampo29'
	 * 
	 * @param campo29
	 */
	public void setCampo29(String campo29)
	{
		this.campo29 = campo29;
	}

	/**
	 * Method 'getCampo30'
	 * 
	 * @return String
	 */
	public String getCampo30()
	{
		return campo30;
	}

	/**
	 * Method 'setCampo30'
	 * 
	 * @param campo30
	 */
	public void setCampo30(String campo30)
	{
		this.campo30 = campo30;
	}

	/**
	 * Method 'getCampo31'
	 * 
	 * @return String
	 */
	public String getCampo31()
	{
		return campo31;
	}

	/**
	 * Method 'setCampo31'
	 * 
	 * @param campo31
	 */
	public void setCampo31(String campo31)
	{
		this.campo31 = campo31;
	}

	/**
	 * Method 'getCampo32'
	 * 
	 * @return String
	 */
	public String getCampo32()
	{
		return campo32;
	}

	/**
	 * Method 'setCampo32'
	 * 
	 * @param campo32
	 */
	public void setCampo32(String campo32)
	{
		this.campo32 = campo32;
	}

	/**
	 * Method 'getCampo33'
	 * 
	 * @return String
	 */
	public String getCampo33()
	{
		return campo33;
	}

	/**
	 * Method 'setCampo33'
	 * 
	 * @param campo33
	 */
	public void setCampo33(String campo33)
	{
		this.campo33 = campo33;
	}

	/**
	 * Method 'getCampo34'
	 * 
	 * @return String
	 */
	public String getCampo34()
	{
		return campo34;
	}

	/**
	 * Method 'setCampo34'
	 * 
	 * @param campo34
	 */
	public void setCampo34(String campo34)
	{
		this.campo34 = campo34;
	}

	/**
	 * Method 'getCampo35'
	 * 
	 * @return String
	 */
	public String getCampo35()
	{
		return campo35;
	}

	/**
	 * Method 'setCampo35'
	 * 
	 * @param campo35
	 */
	public void setCampo35(String campo35)
	{
		this.campo35 = campo35;
	}

	/**
	 * Method 'getCampo36'
	 * 
	 * @return String
	 */
	public String getCampo36()
	{
		return campo36;
	}

	/**
	 * Method 'setCampo36'
	 * 
	 * @param campo36
	 */
	public void setCampo36(String campo36)
	{
		this.campo36 = campo36;
	}

	/**
	 * Method 'getCampo37'
	 * 
	 * @return String
	 */
	public String getCampo37()
	{
		return campo37;
	}

	/**
	 * Method 'setCampo37'
	 * 
	 * @param campo37
	 */
	public void setCampo37(String campo37)
	{
		this.campo37 = campo37;
	}

	/**
	 * Method 'getCampo38'
	 * 
	 * @return String
	 */
	public String getCampo38()
	{
		return campo38;
	}

	/**
	 * Method 'setCampo38'
	 * 
	 * @param campo38
	 */
	public void setCampo38(String campo38)
	{
		this.campo38 = campo38;
	}

	/**
	 * Method 'getCampo39'
	 * 
	 * @return String
	 */
	public String getCampo39()
	{
		return campo39;
	}

	/**
	 * Method 'setCampo39'
	 * 
	 * @param campo39
	 */
	public void setCampo39(String campo39)
	{
		this.campo39 = campo39;
	}

	/**
	 * Method 'getCampo40'
	 * 
	 * @return String
	 */
	public String getCampo40()
	{
		return campo40;
	}

	/**
	 * Method 'setCampo40'
	 * 
	 * @param campo40
	 */
	public void setCampo40(String campo40)
	{
		this.campo40 = campo40;
	}

	/**
	 * Method 'getCampo41'
	 * 
	 * @return String
	 */
	public String getCampo41()
	{
		return campo41;
	}

	/**
	 * Method 'setCampo41'
	 * 
	 * @param campo41
	 */
	public void setCampo41(String campo41)
	{
		this.campo41 = campo41;
	}

	/**
	 * Method 'getCampo42'
	 * 
	 * @return String
	 */
	public String getCampo42()
	{
		return campo42;
	}

	/**
	 * Method 'setCampo42'
	 * 
	 * @param campo42
	 */
	public void setCampo42(String campo42)
	{
		this.campo42 = campo42;
	}

	/**
	 * Method 'getCampo43'
	 * 
	 * @return String
	 */
	public String getCampo43()
	{
		return campo43;
	}

	/**
	 * Method 'setCampo43'
	 * 
	 * @param campo43
	 */
	public void setCampo43(String campo43)
	{
		this.campo43 = campo43;
	}

	/**
	 * Method 'getCampo44'
	 * 
	 * @return String
	 */
	public String getCampo44()
	{
		return campo44;
	}

	/**
	 * Method 'setCampo44'
	 * 
	 * @param campo44
	 */
	public void setCampo44(String campo44)
	{
		this.campo44 = campo44;
	}

	/**
	 * Method 'getCampo45'
	 * 
	 * @return String
	 */
	public String getCampo45()
	{
		return campo45;
	}

	/**
	 * Method 'setCampo45'
	 * 
	 * @param campo45
	 */
	public void setCampo45(String campo45)
	{
		this.campo45 = campo45;
	}

	/**
	 * Method 'getCampo46'
	 * 
	 * @return String
	 */
	public String getCampo46()
	{
		return campo46;
	}

	/**
	 * Method 'setCampo46'
	 * 
	 * @param campo46
	 */
	public void setCampo46(String campo46)
	{
		this.campo46 = campo46;
	}

	/**
	 * Method 'getCampo47'
	 * 
	 * @return String
	 */
	public String getCampo47()
	{
		return campo47;
	}

	/**
	 * Method 'setCampo47'
	 * 
	 * @param campo47
	 */
	public void setCampo47(String campo47)
	{
		this.campo47 = campo47;
	}

	/**
	 * Method 'getCampo48'
	 * 
	 * @return String
	 */
	public String getCampo48()
	{
		return campo48;
	}

	/**
	 * Method 'setCampo48'
	 * 
	 * @param campo48
	 */
	public void setCampo48(String campo48)
	{
		this.campo48 = campo48;
	}

	/**
	 * Method 'getCampo49'
	 * 
	 * @return String
	 */
	public String getCampo49()
	{
		return campo49;
	}

	/**
	 * Method 'setCampo49'
	 * 
	 * @param campo49
	 */
	public void setCampo49(String campo49)
	{
		this.campo49 = campo49;
	}

	/**
	 * Method 'getCampo50'
	 * 
	 * @return String
	 */
	public String getCampo50()
	{
		return campo50;
	}

	/**
	 * Method 'setCampo50'
	 * 
	 * @param campo50
	 */
	public void setCampo50(String campo50)
	{
		this.campo50 = campo50;
	}
	
	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ArrAnualSubstratos)) {
			return false;
		}
		
		final ArrAnualSubstratos _cast = (ArrAnualSubstratos) _other;
		if (anio == null ? _cast.anio != anio : !anio.equals( _cast.anio )) {
			return false;
		}
		
		if (substrato == null ? _cast.substrato != substrato : !substrato.equals( _cast.substrato )) {
			return false;
		}
		
		if (campo1 == null ? _cast.campo1 != campo1 : !campo1.equals( _cast.campo1 )) {
			return false;
		}
		
		if (campo2 == null ? _cast.campo2 != campo2 : !campo2.equals( _cast.campo2 )) {
			return false;
		}
		
		if (campo3 == null ? _cast.campo3 != campo3 : !campo3.equals( _cast.campo3 )) {
			return false;
		}
		
		if (campo4 == null ? _cast.campo4 != campo4 : !campo4.equals( _cast.campo4 )) {
			return false;
		}
		
		if (campo5 == null ? _cast.campo5 != campo5 : !campo5.equals( _cast.campo5 )) {
			return false;
		}
		
		if (campo6 == null ? _cast.campo6 != campo6 : !campo6.equals( _cast.campo6 )) {
			return false;
		}
		
		if (campo7 == null ? _cast.campo7 != campo7 : !campo7.equals( _cast.campo7 )) {
			return false;
		}
		
		if (campo8 == null ? _cast.campo8 != campo8 : !campo8.equals( _cast.campo8 )) {
			return false;
		}
		
		if (campo9 == null ? _cast.campo9 != campo9 : !campo9.equals( _cast.campo9 )) {
			return false;
		}
		
		if (campo10 == null ? _cast.campo10 != campo10 : !campo10.equals( _cast.campo10 )) {
			return false;
		}
		
		if (campo11 == null ? _cast.campo11 != campo11 : !campo11.equals( _cast.campo11 )) {
			return false;
		}
		
		if (campo12 == null ? _cast.campo12 != campo12 : !campo12.equals( _cast.campo12 )) {
			return false;
		}
		
		if (campo13 == null ? _cast.campo13 != campo13 : !campo13.equals( _cast.campo13 )) {
			return false;
		}
		
		if (campo14 == null ? _cast.campo14 != campo14 : !campo14.equals( _cast.campo14 )) {
			return false;
		}
		
		if (campo15 == null ? _cast.campo15 != campo15 : !campo15.equals( _cast.campo15 )) {
			return false;
		}
		
		if (campo16 == null ? _cast.campo16 != campo16 : !campo16.equals( _cast.campo16 )) {
			return false;
		}
		
		if (campo17 == null ? _cast.campo17 != campo17 : !campo17.equals( _cast.campo17 )) {
			return false;
		}
		
		if (campo18 == null ? _cast.campo18 != campo18 : !campo18.equals( _cast.campo18 )) {
			return false;
		}
		
		if (campo19 == null ? _cast.campo19 != campo19 : !campo19.equals( _cast.campo19 )) {
			return false;
		}
		
		if (campo20 == null ? _cast.campo20 != campo20 : !campo20.equals( _cast.campo20 )) {
			return false;
		}
		
		if (campo21 == null ? _cast.campo21 != campo21 : !campo21.equals( _cast.campo21 )) {
			return false;
		}
		
		if (campo22 == null ? _cast.campo22 != campo22 : !campo22.equals( _cast.campo22 )) {
			return false;
		}
		
		if (campo23 == null ? _cast.campo23 != campo23 : !campo23.equals( _cast.campo23 )) {
			return false;
		}
		
		if (campo24 == null ? _cast.campo24 != campo24 : !campo24.equals( _cast.campo24 )) {
			return false;
		}
		
		if (campo25 == null ? _cast.campo25 != campo25 : !campo25.equals( _cast.campo25 )) {
			return false;
		}
		
		if (campo26 == null ? _cast.campo26 != campo26 : !campo26.equals( _cast.campo26 )) {
			return false;
		}
		
		if (campo27 == null ? _cast.campo27 != campo27 : !campo27.equals( _cast.campo27 )) {
			return false;
		}
		
		if (campo28 == null ? _cast.campo28 != campo28 : !campo28.equals( _cast.campo28 )) {
			return false;
		}
		
		if (campo29 == null ? _cast.campo29 != campo29 : !campo29.equals( _cast.campo29 )) {
			return false;
		}
		
		if (campo30 == null ? _cast.campo30 != campo30 : !campo30.equals( _cast.campo30 )) {
			return false;
		}
		
		if (campo31 == null ? _cast.campo31 != campo31 : !campo31.equals( _cast.campo31 )) {
			return false;
		}
		
		if (campo32 == null ? _cast.campo32 != campo32 : !campo32.equals( _cast.campo32 )) {
			return false;
		}
		
		if (campo33 == null ? _cast.campo33 != campo33 : !campo33.equals( _cast.campo33 )) {
			return false;
		}
		
		if (campo34 == null ? _cast.campo34 != campo34 : !campo34.equals( _cast.campo34 )) {
			return false;
		}
		
		if (campo35 == null ? _cast.campo35 != campo35 : !campo35.equals( _cast.campo35 )) {
			return false;
		}
		
		if (campo36 == null ? _cast.campo36 != campo36 : !campo36.equals( _cast.campo36 )) {
			return false;
		}
		
		if (campo37 == null ? _cast.campo37 != campo37 : !campo37.equals( _cast.campo37 )) {
			return false;
		}
		
		if (campo38 == null ? _cast.campo38 != campo38 : !campo38.equals( _cast.campo38 )) {
			return false;
		}
		
		if (campo39 == null ? _cast.campo39 != campo39 : !campo39.equals( _cast.campo39 )) {
			return false;
		}
		
		if (campo40 == null ? _cast.campo40 != campo40 : !campo40.equals( _cast.campo40 )) {
			return false;
		}
		
		if (campo41 == null ? _cast.campo41 != campo41 : !campo41.equals( _cast.campo41 )) {
			return false;
		}
		
		if (campo42 == null ? _cast.campo42 != campo42 : !campo42.equals( _cast.campo42 )) {
			return false;
		}
		
		if (campo43 == null ? _cast.campo43 != campo43 : !campo43.equals( _cast.campo43 )) {
			return false;
		}
		
		if (campo44 == null ? _cast.campo44 != campo44 : !campo44.equals( _cast.campo44 )) {
			return false;
		}
		
		if (campo45 == null ? _cast.campo45 != campo45 : !campo45.equals( _cast.campo45 )) {
			return false;
		}
		
		if (campo46 == null ? _cast.campo46 != campo46 : !campo46.equals( _cast.campo46 )) {
			return false;
		}
		
		if (campo47 == null ? _cast.campo47 != campo47 : !campo47.equals( _cast.campo47 )) {
			return false;
		}
		
		if (campo48 == null ? _cast.campo48 != campo48 : !campo48.equals( _cast.campo48 )) {
			return false;
		}
		
		if (campo49 == null ? _cast.campo49 != campo49 : !campo49.equals( _cast.campo49 )) {
			return false;
		}
		
		if (campo50 == null ? _cast.campo50 != campo50 : !campo50.equals( _cast.campo50 )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (anio != null) {
			_hashCode = 29 * _hashCode + anio.hashCode();
		}
		
		if (substrato != null) {
			_hashCode = 29 * _hashCode + substrato.hashCode();
		}
		
		if (campo1 != null) {
			_hashCode = 29 * _hashCode + campo1.hashCode();
		}
		
		if (campo2 != null) {
			_hashCode = 29 * _hashCode + campo2.hashCode();
		}
		
		if (campo3 != null) {
			_hashCode = 29 * _hashCode + campo3.hashCode();
		}
		
		if (campo4 != null) {
			_hashCode = 29 * _hashCode + campo4.hashCode();
		}
		
		if (campo5 != null) {
			_hashCode = 29 * _hashCode + campo5.hashCode();
		}
		
		if (campo6 != null) {
			_hashCode = 29 * _hashCode + campo6.hashCode();
		}
		
		if (campo7 != null) {
			_hashCode = 29 * _hashCode + campo7.hashCode();
		}
		
		if (campo8 != null) {
			_hashCode = 29 * _hashCode + campo8.hashCode();
		}
		
		if (campo9 != null) {
			_hashCode = 29 * _hashCode + campo9.hashCode();
		}
		
		if (campo10 != null) {
			_hashCode = 29 * _hashCode + campo10.hashCode();
		}
		
		if (campo11 != null) {
			_hashCode = 29 * _hashCode + campo11.hashCode();
		}
		
		if (campo12 != null) {
			_hashCode = 29 * _hashCode + campo12.hashCode();
		}
		
		if (campo13 != null) {
			_hashCode = 29 * _hashCode + campo13.hashCode();
		}
		
		if (campo14 != null) {
			_hashCode = 29 * _hashCode + campo14.hashCode();
		}
		
		if (campo15 != null) {
			_hashCode = 29 * _hashCode + campo15.hashCode();
		}
		
		if (campo16 != null) {
			_hashCode = 29 * _hashCode + campo16.hashCode();
		}
		
		if (campo17 != null) {
			_hashCode = 29 * _hashCode + campo17.hashCode();
		}
		
		if (campo18 != null) {
			_hashCode = 29 * _hashCode + campo18.hashCode();
		}
		
		if (campo19 != null) {
			_hashCode = 29 * _hashCode + campo19.hashCode();
		}
		
		if (campo20 != null) {
			_hashCode = 29 * _hashCode + campo20.hashCode();
		}
		
		if (campo21 != null) {
			_hashCode = 29 * _hashCode + campo21.hashCode();
		}
		
		if (campo22 != null) {
			_hashCode = 29 * _hashCode + campo22.hashCode();
		}
		
		if (campo23 != null) {
			_hashCode = 29 * _hashCode + campo23.hashCode();
		}
		
		if (campo24 != null) {
			_hashCode = 29 * _hashCode + campo24.hashCode();
		}
		
		if (campo25 != null) {
			_hashCode = 29 * _hashCode + campo25.hashCode();
		}
		
		if (campo26 != null) {
			_hashCode = 29 * _hashCode + campo26.hashCode();
		}
		
		if (campo27 != null) {
			_hashCode = 29 * _hashCode + campo27.hashCode();
		}
		
		if (campo28 != null) {
			_hashCode = 29 * _hashCode + campo28.hashCode();
		}
		
		if (campo29 != null) {
			_hashCode = 29 * _hashCode + campo29.hashCode();
		}
		
		if (campo30 != null) {
			_hashCode = 29 * _hashCode + campo30.hashCode();
		}
		
		if (campo31 != null) {
			_hashCode = 29 * _hashCode + campo31.hashCode();
		}
		
		if (campo32 != null) {
			_hashCode = 29 * _hashCode + campo32.hashCode();
		}
		
		if (campo33 != null) {
			_hashCode = 29 * _hashCode + campo33.hashCode();
		}
		
		if (campo34 != null) {
			_hashCode = 29 * _hashCode + campo34.hashCode();
		}
		
		if (campo35 != null) {
			_hashCode = 29 * _hashCode + campo35.hashCode();
		}
		
		if (campo36 != null) {
			_hashCode = 29 * _hashCode + campo36.hashCode();
		}
		
		if (campo37 != null) {
			_hashCode = 29 * _hashCode + campo37.hashCode();
		}
		
		if (campo38 != null) {
			_hashCode = 29 * _hashCode + campo38.hashCode();
		}
		
		if (campo39 != null) {
			_hashCode = 29 * _hashCode + campo39.hashCode();
		}
		
		if (campo40 != null) {
			_hashCode = 29 * _hashCode + campo40.hashCode();
		}
		
		if (campo41 != null) {
			_hashCode = 29 * _hashCode + campo41.hashCode();
		}
		
		if (campo42 != null) {
			_hashCode = 29 * _hashCode + campo42.hashCode();
		}
		
		if (campo43 != null) {
			_hashCode = 29 * _hashCode + campo43.hashCode();
		}
		
		if (campo44 != null) {
			_hashCode = 29 * _hashCode + campo44.hashCode();
		}
		
		if (campo45 != null) {
			_hashCode = 29 * _hashCode + campo45.hashCode();
		}
		
		if (campo46 != null) {
			_hashCode = 29 * _hashCode + campo46.hashCode();
		}
		
		if (campo47 != null) {
			_hashCode = 29 * _hashCode + campo47.hashCode();
		}
		
		if (campo48 != null) {
			_hashCode = 29 * _hashCode + campo48.hashCode();
		}
		
		if (campo49 != null) {
			_hashCode = 29 * _hashCode + campo49.hashCode();
		}
		
		if (campo50 != null) {
			_hashCode = 29 * _hashCode + campo50.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ArrAnualSubstratosPk
	 */
	public ArrAnualSubstratosPk createPk()
	{
		return new ArrAnualSubstratosPk(anio);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.sorin.idea.dto.ArrAnualSubstratos: " );
		ret.append( "anio=" + anio );
		ret.append( ", substrato=" + substrato );
		ret.append( ", campo1=" + campo1 );
		ret.append( ", campo2=" + campo2 );
		ret.append( ", campo3=" + campo3 );
		ret.append( ", campo4=" + campo4 );
		ret.append( ", campo5=" + campo5 );
		ret.append( ", campo6=" + campo6 );
		ret.append( ", campo7=" + campo7 );
		ret.append( ", campo8=" + campo8 );
		ret.append( ", campo9=" + campo9 );
		ret.append( ", campo10=" + campo10 );
		ret.append( ", campo11=" + campo11 );
		ret.append( ", campo12=" + campo12 );
		ret.append( ", campo13=" + campo13 );
		ret.append( ", campo14=" + campo14 );
		ret.append( ", campo15=" + campo15 );
		ret.append( ", campo16=" + campo16 );
		ret.append( ", campo17=" + campo17 );
		ret.append( ", campo18=" + campo18 );
		ret.append( ", campo19=" + campo19 );
		ret.append( ", campo20=" + campo20 );
		ret.append( ", campo21=" + campo21 );
		ret.append( ", campo22=" + campo22 );
		ret.append( ", campo23=" + campo23 );
		ret.append( ", campo24=" + campo24 );
		ret.append( ", campo25=" + campo25 );
		ret.append( ", campo26=" + campo26 );
		ret.append( ", campo27=" + campo27 );
		ret.append( ", campo28=" + campo28 );
		ret.append( ", campo29=" + campo29 );
		ret.append( ", campo30=" + campo30 );
		ret.append( ", campo31=" + campo31 );
		ret.append( ", campo32=" + campo32 );
		ret.append( ", campo33=" + campo33 );
		ret.append( ", campo34=" + campo34 );
		ret.append( ", campo35=" + campo35 );
		ret.append( ", campo36=" + campo36 );
		ret.append( ", campo37=" + campo37 );
		ret.append( ", campo38=" + campo38 );
		ret.append( ", campo39=" + campo39 );
		ret.append( ", campo40=" + campo40 );
		ret.append( ", campo41=" + campo41 );
		ret.append( ", campo42=" + campo42 );
		ret.append( ", campo43=" + campo43 );
		ret.append( ", campo44=" + campo44 );
		ret.append( ", campo45=" + campo45 );
		ret.append( ", campo46=" + campo46 );
		ret.append( ", campo47=" + campo47 );
		ret.append( ", campo48=" + campo48 );
		ret.append( ", campo49=" + campo49 );
		ret.append( ", campo50=" + campo50 );
		return ret.toString();
	}
	public String getCatRFFasica() {
		return catRFFasica;
	}
	public void setCatRFFasica(String catRFFasica) {
		this.catRFFasica = catRFFasica;
	}
	public String getCatRFIrrig() {
		return catRFIrrig;
	}
	public void setCatRFIrrig(String catRFIrrig) {
		this.catRFIrrig = catRFIrrig;
	}
	public String getCatLaser() {
		return catLaser;
	}
	public void setCatLaser(String catLaser) {
		this.catLaser = catLaser;
	}

}
