/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import java.io.Serializable;
import java.util.*;

import com.sorin.idea.dao.*;
import com.sorin.idea.exceptions.*;
import com.sorin.idea.factory.*;

public class ImpIndicacion implements Serializable
{
	/** 
	 * This attribute maps to the column IDINDICACION in the imp_indicacion table.
	 */
	protected Integer idindicacion;

	/** 
	 * This attribute maps to the column RITMOBASAL in the imp_indicacion table.
	 */
	protected Integer ritmobasal;

	/** 
	 * This attribute maps to the column CONDUCAV in the imp_indicacion table.
	 */
	protected Integer conducav;

	/** 
	 * This attribute maps to the column QRS in the imp_indicacion table.
	 */
	protected Integer qrs;

	/** 
	 * This attribute maps to the column ANCHURAQRS in the imp_indicacion table.
	 */
	protected String anchuraqrs;

	/** 
	 * This attribute maps to the column FEYECCION in the imp_indicacion table.
	 */
	protected Integer feyeccion;

	/** 
	 * This attribute maps to the column NYHA in the imp_indicacion table.
	 */
	protected Integer nyha;

	/** 
	 * This attribute maps to the column CARDIOPATIA in the imp_indicacion table.
	 */
	protected Integer cardiopatia;

	/** 
	 * This attribute maps to the column AEVOLUCION in the imp_indicacion table.
	 */
	protected String aevolucion;

	/** 
	 * This attribute maps to the column REVASC in the imp_indicacion table.
	 */
	protected Short revasc;

	/** 
	 * This attribute maps to the column INFPREV in the imp_indicacion table.
	 */
	protected Short infprev;

	/** 
	 * This attribute maps to the column ANIO in the imp_indicacion table.
	 */
	protected String anio;

	/** 
	 * This attribute maps to the column LOCALIZACION in the imp_indicacion table.
	 */
	protected Integer localizacion;

	/** 
	 * This attribute maps to the column INSRENAL in the imp_indicacion table.
	 */
	protected Short insrenal;

	/** 
	 * This attribute maps to the column ANTFA in the imp_indicacion table.
	 */
	protected Short antfa;

	/** 
	 * This attribute maps to the column DIABETES in the imp_indicacion table.
	 */
	protected Short diabetes;

	/** 
	 * This attribute maps to the column HIPERTENSION in the imp_indicacion table.
	 */
	protected Short hipertension;

	/** 
	 * This attribute maps to the column MUERTESUBITA in the imp_indicacion table.
	 */
	protected Short muertesubita;

	/** 
	 * This attribute maps to the column FUMADOR in the imp_indicacion table.
	 */
	protected Short fumador;

	/** 
	 * This attribute maps to the column HIPERCOLEST in the imp_indicacion table.
	 */
	protected Short hipercolest;

	/** 
	 * This attribute maps to the column ACV in the imp_indicacion table.
	 */
	protected Short acv;

	/** 
	 * This attribute maps to the column ARRITMIAS in the imp_indicacion table.
	 */
	protected Integer arritmias;

	/** 
	 * This attribute maps to the column EEF in the imp_indicacion table.
	 */
	protected Integer eef;

	/** 
	 * This attribute maps to the column ETIOLOGIA in the imp_indicacion table.
	 */
	protected Integer etiologia;

	/** 
	 * This attribute maps to the column OTRA in the imp_indicacion table.
	 */
	protected String otra;
	
	protected ArrayList<ImpSintomas> sintomas;
	protected boolean ic;
	protected boolean avent;
	protected boolean eefprev;
	protected boolean isquemica;
	protected boolean revascularizacion;
	protected boolean infartoprev;
	protected boolean anteinsrenal;
	protected boolean antefa;
	protected boolean antediab;
	protected boolean antehipertens;
	protected boolean antefam;
	protected boolean antetabaq;
	protected boolean antehipercol;
	protected boolean anteacv;

	/**
	 * Method 'ImpIndicacion'
	 * 
	 */
	public ImpIndicacion()
	{
		this.sintomas = new ArrayList<ImpSintomas>();
	}

	/**
	 * Method 'getIdindicacion'
	 * 
	 * @return Integer
	 */
	public Integer getIdindicacion()
	{
		return idindicacion;
	}

	/**
	 * Method 'setIdindicacion'
	 * 
	 * @param idindicacion
	 */
	public void setIdindicacion(Integer idindicacion)
	{
		this.idindicacion = idindicacion;
	}

	/**
	 * Method 'getRitmobasal'
	 * 
	 * @return Integer
	 */
	public Integer getRitmobasal()
	{
		return ritmobasal;
	}

	/**
	 * Method 'setRitmobasal'
	 * 
	 * @param ritmobasal
	 */
	public void setRitmobasal(Integer ritmobasal)
	{
		this.ritmobasal = ritmobasal;
	}

	/**
	 * Method 'getConducav'
	 * 
	 * @return Integer
	 */
	public Integer getConducav()
	{
		return conducav;
	}

	/**
	 * Method 'setConducav'
	 * 
	 * @param conducav
	 */
	public void setConducav(Integer conducav)
	{
		this.conducav = conducav;
	}

	/**
	 * Method 'getQrs'
	 * 
	 * @return Integer
	 */
	public Integer getQrs()
	{
		return qrs;
	}

	/**
	 * Method 'setQrs'
	 * 
	 * @param qrs
	 */
	public void setQrs(Integer qrs)
	{
		this.qrs = qrs;
	}

	/**
	 * Method 'getAnchuraqrs'
	 * 
	 * @return String
	 */
	public String getAnchuraqrs()
	{
		return anchuraqrs;
	}

	/**
	 * Method 'setAnchuraqrs'
	 * 
	 * @param anchuraqrs
	 */
	public void setAnchuraqrs(String anchuraqrs)
	{
		this.anchuraqrs = anchuraqrs;
	}

	/**
	 * Method 'getFeyeccion'
	 * 
	 * @return Integer
	 */
	public Integer getFeyeccion()
	{
		return feyeccion;
	}

	/**
	 * Method 'setFeyeccion'
	 * 
	 * @param feyeccion
	 */
	public void setFeyeccion(Integer feyeccion)
	{
		this.feyeccion = feyeccion;
	}

	/**
	 * Method 'getNyha'
	 * 
	 * @return Integer
	 */
	public Integer getNyha()
	{
		return nyha;
	}

	/**
	 * Method 'setNyha'
	 * 
	 * @param nyha
	 */
	public void setNyha(Integer nyha)
	{
		this.nyha = nyha;
	}

	/**
	 * Method 'getCardiopatia'
	 * 
	 * @return Integer
	 */
	public Integer getCardiopatia()
	{
		return cardiopatia;
	}

	/**
	 * Method 'setCardiopatia'
	 * 
	 * @param cardiopatia
	 */
	public void setCardiopatia(Integer cardiopatia)
	{
		this.cardiopatia = cardiopatia;
	}

	/**
	 * Method 'getAevolucion'
	 * 
	 * @return String
	 */
	public String getAevolucion()
	{
		return aevolucion;
	}

	/**
	 * Method 'setAevolucion'
	 * 
	 * @param aevolucion
	 */
	public void setAevolucion(String aevolucion)
	{
		this.aevolucion = aevolucion;
	}

	/**
	 * Method 'getRevasc'
	 * 
	 * @return Short
	 */
	public Short getRevasc()
	{
		return revasc;
	}

	/**
	 * Method 'setRevasc'
	 * 
	 * @param revasc
	 */
	public void setRevasc(Short revasc)
	{
		this.revasc = revasc;
	}

	/**
	 * Method 'getInfprev'
	 * 
	 * @return Short
	 */
	public Short getInfprev()
	{
		return infprev;
	}

	/**
	 * Method 'setInfprev'
	 * 
	 * @param infprev
	 */
	public void setInfprev(Short infprev)
	{
		this.infprev = infprev;
	}

	/**
	 * Method 'getAnio'
	 * 
	 * @return String
	 */
	public String getAnio()
	{
		return anio;
	}

	/**
	 * Method 'setAnio'
	 * 
	 * @param anio
	 */
	public void setAnio(String anio)
	{
		this.anio = anio;
	}

	/**
	 * Method 'getLocalizacion'
	 * 
	 * @return Integer
	 */
	public Integer getLocalizacion()
	{
		return localizacion;
	}

	/**
	 * Method 'setLocalizacion'
	 * 
	 * @param localizacion
	 */
	public void setLocalizacion(Integer localizacion)
	{
		this.localizacion = localizacion;
	}

	/**
	 * Method 'getInsrenal'
	 * 
	 * @return Short
	 */
	public Short getInsrenal()
	{
		return insrenal;
	}

	/**
	 * Method 'setInsrenal'
	 * 
	 * @param insrenal
	 */
	public void setInsrenal(Short insrenal)
	{
		this.insrenal = insrenal;
	}

	/**
	 * Method 'getAntfa'
	 * 
	 * @return Short
	 */
	public Short getAntfa()
	{
		return antfa;
	}

	/**
	 * Method 'setAntfa'
	 * 
	 * @param antfa
	 */
	public void setAntfa(Short antfa)
	{
		this.antfa = antfa;
	}

	/**
	 * Method 'getDiabetes'
	 * 
	 * @return Short
	 */
	public Short getDiabetes()
	{
		return diabetes;
	}

	/**
	 * Method 'setDiabetes'
	 * 
	 * @param diabetes
	 */
	public void setDiabetes(Short diabetes)
	{
		this.diabetes = diabetes;
	}

	/**
	 * Method 'getHipertension'
	 * 
	 * @return Short
	 */
	public Short getHipertension()
	{
		return hipertension;
	}

	/**
	 * Method 'setHipertension'
	 * 
	 * @param hipertension
	 */
	public void setHipertension(Short hipertension)
	{
		this.hipertension = hipertension;
	}

	/**
	 * Method 'getMuertesubita'
	 * 
	 * @return Short
	 */
	public Short getMuertesubita()
	{
		return muertesubita;
	}

	/**
	 * Method 'setMuertesubita'
	 * 
	 * @param muertesubita
	 */
	public void setMuertesubita(Short muertesubita)
	{
		this.muertesubita = muertesubita;
	}

	/**
	 * Method 'getFumador'
	 * 
	 * @return Short
	 */
	public Short getFumador()
	{
		return fumador;
	}

	/**
	 * Method 'setFumador'
	 * 
	 * @param fumador
	 */
	public void setFumador(Short fumador)
	{
		this.fumador = fumador;
	}

	/**
	 * Method 'getHipercolest'
	 * 
	 * @return Short
	 */
	public Short getHipercolest()
	{
		return hipercolest;
	}

	/**
	 * Method 'setHipercolest'
	 * 
	 * @param hipercolest
	 */
	public void setHipercolest(Short hipercolest)
	{
		this.hipercolest = hipercolest;
	}

	/**
	 * Method 'getAcv'
	 * 
	 * @return Short
	 */
	public Short getAcv()
	{
		return acv;
	}

	/**
	 * Method 'setAcv'
	 * 
	 * @param acv
	 */
	public void setAcv(Short acv)
	{
		this.acv = acv;
	}

	/**
	 * Method 'getArritmias'
	 * 
	 * @return Integer
	 */
	public Integer getArritmias()
	{
		return arritmias;
	}

	/**
	 * Method 'setArritmias'
	 * 
	 * @param arritmias
	 */
	public void setArritmias(Integer arritmias)
	{
		this.arritmias = arritmias;
	}

	/**
	 * Method 'getEef'
	 * 
	 * @return Integer
	 */
	public Integer getEef()
	{
		return eef;
	}

	/**
	 * Method 'setEef'
	 * 
	 * @param eef
	 */
	public void setEef(Integer eef)
	{
		this.eef = eef;
	}

	/**
	 * Method 'getEtiologia'
	 * 
	 * @return Integer
	 */
	public Integer getEtiologia()
	{
		return etiologia;
	}

	/**
	 * Method 'setEtiologia'
	 * 
	 * @param etiologia
	 */
	public void setEtiologia(Integer etiologia)
	{
		this.etiologia = etiologia;
	}

	/**
	 * Method 'getOtra'
	 * 
	 * @return String
	 */
	public String getOtra()
	{
		return otra;
	}

	/**
	 * Method 'setOtra'
	 * 
	 * @param otra
	 */
	public void setOtra(String otra)
	{
		this.otra = otra;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ImpIndicacion)) {
			return false;
		}
		
		final ImpIndicacion _cast = (ImpIndicacion) _other;
		if (idindicacion == null ? _cast.idindicacion != idindicacion : !idindicacion.equals( _cast.idindicacion )) {
			return false;
		}
		
		if (ritmobasal == null ? _cast.ritmobasal != ritmobasal : !ritmobasal.equals( _cast.ritmobasal )) {
			return false;
		}
		
		if (conducav == null ? _cast.conducav != conducav : !conducav.equals( _cast.conducav )) {
			return false;
		}
		
		if (qrs == null ? _cast.qrs != qrs : !qrs.equals( _cast.qrs )) {
			return false;
		}
		
		if (anchuraqrs == null ? _cast.anchuraqrs != anchuraqrs : !anchuraqrs.equals( _cast.anchuraqrs )) {
			return false;
		}
		
		if (feyeccion == null ? _cast.feyeccion != feyeccion : !feyeccion.equals( _cast.feyeccion )) {
			return false;
		}
		
		if (nyha == null ? _cast.nyha != nyha : !nyha.equals( _cast.nyha )) {
			return false;
		}
		
		if (cardiopatia == null ? _cast.cardiopatia != cardiopatia : !cardiopatia.equals( _cast.cardiopatia )) {
			return false;
		}
		
		if (aevolucion == null ? _cast.aevolucion != aevolucion : !aevolucion.equals( _cast.aevolucion )) {
			return false;
		}
		
		if (revasc == null ? _cast.revasc != revasc : !revasc.equals( _cast.revasc )) {
			return false;
		}
		
		if (infprev == null ? _cast.infprev != infprev : !infprev.equals( _cast.infprev )) {
			return false;
		}
		
		if (anio == null ? _cast.anio != anio : !anio.equals( _cast.anio )) {
			return false;
		}
		
		if (localizacion == null ? _cast.localizacion != localizacion : !localizacion.equals( _cast.localizacion )) {
			return false;
		}
		
		if (insrenal == null ? _cast.insrenal != insrenal : !insrenal.equals( _cast.insrenal )) {
			return false;
		}
		
		if (antfa == null ? _cast.antfa != antfa : !antfa.equals( _cast.antfa )) {
			return false;
		}
		
		if (diabetes == null ? _cast.diabetes != diabetes : !diabetes.equals( _cast.diabetes )) {
			return false;
		}
		
		if (hipertension == null ? _cast.hipertension != hipertension : !hipertension.equals( _cast.hipertension )) {
			return false;
		}
		
		if (muertesubita == null ? _cast.muertesubita != muertesubita : !muertesubita.equals( _cast.muertesubita )) {
			return false;
		}
		
		if (fumador == null ? _cast.fumador != fumador : !fumador.equals( _cast.fumador )) {
			return false;
		}
		
		if (hipercolest == null ? _cast.hipercolest != hipercolest : !hipercolest.equals( _cast.hipercolest )) {
			return false;
		}
		
		if (acv == null ? _cast.acv != acv : !acv.equals( _cast.acv )) {
			return false;
		}
		
		if (arritmias == null ? _cast.arritmias != arritmias : !arritmias.equals( _cast.arritmias )) {
			return false;
		}
		
		if (eef == null ? _cast.eef != eef : !eef.equals( _cast.eef )) {
			return false;
		}
		
		if (etiologia == null ? _cast.etiologia != etiologia : !etiologia.equals( _cast.etiologia )) {
			return false;
		}
		
		if (otra == null ? _cast.otra != otra : !otra.equals( _cast.otra )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idindicacion != null) {
			_hashCode = 29 * _hashCode + idindicacion.hashCode();
		}
		
		if (ritmobasal != null) {
			_hashCode = 29 * _hashCode + ritmobasal.hashCode();
		}
		
		if (conducav != null) {
			_hashCode = 29 * _hashCode + conducav.hashCode();
		}
		
		if (qrs != null) {
			_hashCode = 29 * _hashCode + qrs.hashCode();
		}
		
		if (anchuraqrs != null) {
			_hashCode = 29 * _hashCode + anchuraqrs.hashCode();
		}
		
		if (feyeccion != null) {
			_hashCode = 29 * _hashCode + feyeccion.hashCode();
		}
		
		if (nyha != null) {
			_hashCode = 29 * _hashCode + nyha.hashCode();
		}
		
		if (cardiopatia != null) {
			_hashCode = 29 * _hashCode + cardiopatia.hashCode();
		}
		
		if (aevolucion != null) {
			_hashCode = 29 * _hashCode + aevolucion.hashCode();
		}
		
		if (revasc != null) {
			_hashCode = 29 * _hashCode + revasc.hashCode();
		}
		
		if (infprev != null) {
			_hashCode = 29 * _hashCode + infprev.hashCode();
		}
		
		if (anio != null) {
			_hashCode = 29 * _hashCode + anio.hashCode();
		}
		
		if (localizacion != null) {
			_hashCode = 29 * _hashCode + localizacion.hashCode();
		}
		
		if (insrenal != null) {
			_hashCode = 29 * _hashCode + insrenal.hashCode();
		}
		
		if (antfa != null) {
			_hashCode = 29 * _hashCode + antfa.hashCode();
		}
		
		if (diabetes != null) {
			_hashCode = 29 * _hashCode + diabetes.hashCode();
		}
		
		if (hipertension != null) {
			_hashCode = 29 * _hashCode + hipertension.hashCode();
		}
		
		if (muertesubita != null) {
			_hashCode = 29 * _hashCode + muertesubita.hashCode();
		}
		
		if (fumador != null) {
			_hashCode = 29 * _hashCode + fumador.hashCode();
		}
		
		if (hipercolest != null) {
			_hashCode = 29 * _hashCode + hipercolest.hashCode();
		}
		
		if (acv != null) {
			_hashCode = 29 * _hashCode + acv.hashCode();
		}
		
		if (arritmias != null) {
			_hashCode = 29 * _hashCode + arritmias.hashCode();
		}
		
		if (eef != null) {
			_hashCode = 29 * _hashCode + eef.hashCode();
		}
		
		if (etiologia != null) {
			_hashCode = 29 * _hashCode + etiologia.hashCode();
		}
		
		if (otra != null) {
			_hashCode = 29 * _hashCode + otra.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ImpIndicacionPk
	 */
	public ImpIndicacionPk createPk()
	{
		return new ImpIndicacionPk(idindicacion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "hvn.apl.jProyecto2011.dto.ImpIndicacion: " );
		ret.append( "idindicacion=" + idindicacion );
		ret.append( ", ritmobasal=" + ritmobasal );
		ret.append( ", conducav=" + conducav );
		ret.append( ", qrs=" + qrs );
		ret.append( ", anchuraqrs=" + anchuraqrs );
		ret.append( ", feyeccion=" + feyeccion );
		ret.append( ", nyha=" + nyha );
		ret.append( ", cardiopatia=" + cardiopatia );
		ret.append( ", aevolucion=" + aevolucion );
		ret.append( ", revasc=" + revasc );
		ret.append( ", infprev=" + infprev );
		ret.append( ", anio=" + anio );
		ret.append( ", localizacion=" + localizacion );
		ret.append( ", insrenal=" + insrenal );
		ret.append( ", antfa=" + antfa );
		ret.append( ", diabetes=" + diabetes );
		ret.append( ", hipertension=" + hipertension );
		ret.append( ", muertesubita=" + muertesubita );
		ret.append( ", fumador=" + fumador );
		ret.append( ", hipercolest=" + hipercolest );
		ret.append( ", acv=" + acv );
		ret.append( ", arritmias=" + arritmias );
		ret.append( ", eef=" + eef );
		ret.append( ", etiologia=" + etiologia );
		ret.append( ", otra=" + otra );
		return ret.toString();
	}
	public ArrayList<ImpSintomas> getSintomas() {
		return sintomas;
	}

	public void setSintomas(ArrayList<ImpSintomas> sintomas) {
		this.sintomas = sintomas;
	}

	public boolean isIc() {
		return ic;
	}

	public void setIc(boolean ic) {
		this.ic = ic;
	}

	public boolean isAvent() {
		return avent;
	}

	public void setAvent(boolean avent) {
		this.avent = avent;
	}

	public boolean isEefprev() {
		return eefprev;
	}

	public void setEefprev(boolean eefprev) {
		this.eefprev = eefprev;
	}

	public boolean isRevascularizacion() {
		return revascularizacion;
	}

	public void setRevascularizacion(boolean revascularizacion) {
		this.revascularizacion = revascularizacion;
	}

	public boolean isInfartoprev() {
		return infartoprev;
	}

	public void setInfartoprev(boolean infartoprev) {
		this.infartoprev = infartoprev;
	}

	public boolean isIsquemica() {
		return isquemica;
	}

	public void setIsquemica(boolean isquemica) {
		this.isquemica = isquemica;
	}

	public boolean isAnteinsrenal() {
		return anteinsrenal;
	}

	public void setAnteinsrenal(boolean anteinsrenal) {
		this.anteinsrenal = anteinsrenal;
	}

	public boolean isAntefa() {
		return antefa;
	}

	public void setAntefa(boolean antefa) {
		this.antefa = antefa;
	}

	public boolean isAntediab() {
		return antediab;
	}

	public void setAntediab(boolean antediab) {
		this.antediab = antediab;
	}

	public boolean isAntehipertens() {
		return antehipertens;
	}

	public void setAntehipertens(boolean antehipertens) {
		this.antehipertens = antehipertens;
	}

	public boolean isAntefam() {
		return antefam;
	}

	public void setAntefam(boolean antefam) {
		this.antefam = antefam;
	}

	public boolean isAntetabaq() {
		return antetabaq;
	}

	public void setAntetabaq(boolean antetabaq) {
		this.antetabaq = antetabaq;
	}

	public boolean isAntehipercol() {
		return antehipercol;
	}

	public void setAntehipercol(boolean antehipercol) {
		this.antehipercol = antehipercol;
	}

	public boolean isAnteacv() {
		return anteacv;
	}

	public void setAnteacv(boolean anteacv) {
		this.anteacv = anteacv;
	}

}
