/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;

import com.sorin.idea.dao.RcPsicoSituacionLaboralDao;
import com.sorin.idea.dto.RcPsicoSituacionLaboral;
import com.sorin.idea.dto.RcPsicoSituacionLaboralPk;
import com.sorin.idea.exceptions.RcPsicoSituacionLaboralDaoException;
import com.sorin.idea.exceptions.RcRehaProbSensorialesDaoException;

public class RcPsicoSituacionLaboralDaoImpl extends AbstractDAO implements RcPsicoSituacionLaboralDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_SITUACION_LABORAL, SITUACION FROM " + getTableName() + "";

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT_INNER_JOIN = "SELECT " + getTableName() + ".ID_SITUACION_LABORAL, " + getTableName() + ".SITUACION FROM " + getTableName() + "";

	
	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_SITUACION_LABORAL, SITUACION ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_SITUACION_LABORAL = ?, SITUACION = ? WHERE ID_SITUACION_LABORAL = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_SITUACION_LABORAL = ?";

	/** 
	 * Index of column ID_SITUACION_LABORAL
	 */
	protected static final int COLUMN_ID_SITUACION_LABORAL = 1;

	/** 
	 * Index of column SITUACION
	 */
	protected static final int COLUMN_SITUACION = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column ID_SITUACION_LABORAL
	 */
	protected static final int PK_COLUMN_ID_SITUACION_LABORAL = 1;

	/** 
	 * Inserts a new row in the RC_PSICO_SITUACION_LABORAL table.
	 */
	public RcPsicoSituacionLaboralPk insert(RcPsicoSituacionLaboral dto) throws RcPsicoSituacionLaboralDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdSituacionLaboralModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_SITUACION_LABORAL" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isSituacionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "SITUACION" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdSituacionLaboralModified()) {
				stmt.setLong( index++, dto.getIdSituacionLaboral() );
			}
		
			if (dto.isSituacionModified()) {
				stmt.setString( index++, dto.getSituacion() );
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			throw new RcPsicoSituacionLaboralDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the RC_PSICO_SITUACION_LABORAL table.
	 */
	public void update(RcPsicoSituacionLaboralPk pk, RcPsicoSituacionLaboral dto) throws RcPsicoSituacionLaboralDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdSituacionLaboralModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_SITUACION_LABORAL=?" );
				modified=true;
			}
		
			if (dto.isSituacionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "SITUACION=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE ID_SITUACION_LABORAL=?" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdSituacionLaboralModified()) {
				stmt.setLong( index++, dto.getIdSituacionLaboral() );
			}
		
			if (dto.isSituacionModified()) {
				stmt.setString( index++, dto.getSituacion() );
			}
		
			stmt.setLong( index++, pk.getIdSituacionLaboral() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new RcPsicoSituacionLaboralDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the RC_PSICO_SITUACION_LABORAL table.
	 */
	public void delete(RcPsicoSituacionLaboralPk pk) throws RcPsicoSituacionLaboralDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getIdSituacionLaboral() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		}
		catch (Exception _e) {
			throw new RcPsicoSituacionLaboralDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the RC_PSICO_SITUACION_LABORAL table that matches the specified primary-key value.
	 */
	public RcPsicoSituacionLaboral findByPrimaryKey(RcPsicoSituacionLaboralPk pk) throws RcPsicoSituacionLaboralDaoException
	{
		return findByPrimaryKey( pk.getIdSituacionLaboral() );
	}

	/** 
	 * Returns all rows from the RC_PSICO_SITUACION_LABORAL table that match the criteria 'ID_SITUACION_LABORAL = :idSituacionLaboral'.
	 */
	public RcPsicoSituacionLaboral findByPrimaryKey(long idSituacionLaboral) throws RcPsicoSituacionLaboralDaoException
	{
		RcPsicoSituacionLaboral ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_SITUACION_LABORAL = ?", new Object[] {  new Long(idSituacionLaboral) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the RC_PSICO_SITUACION_LABORAL table that match the criteria ''.
	 */
	public RcPsicoSituacionLaboral[] findAll() throws RcPsicoSituacionLaboralDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_SITUACION_LABORAL", null );
	}

	/** 
	 * Returns all rows from the RC_PSICO_SITUACION_LABORAL table that match the criteria 'ID_SITUACION_LABORAL = :idSituacionLaboral'.
	 */
	public RcPsicoSituacionLaboral[] findWhereIdSituacionLaboralEquals(long idSituacionLaboral) throws RcPsicoSituacionLaboralDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_SITUACION_LABORAL = ? ORDER BY ID_SITUACION_LABORAL", new Object[] {  new Long(idSituacionLaboral) } );
	}

	/** 
	 * Returns all rows from the RC_PSICO_SITUACION_LABORAL table that match the criteria 'SITUACION = :situacion'.
	 */
	public RcPsicoSituacionLaboral[] findWhereSituacionEquals(String situacion) throws RcPsicoSituacionLaboralDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SITUACION = ? ORDER BY SITUACION", new Object[] { situacion } );
	}

	/**
	 * Method 'RcPsicoSituacionLaboralDaoImpl'
	 * 
	 */
	public RcPsicoSituacionLaboralDaoImpl()
	{
	}

	/**
	 * Method 'RcPsicoSituacionLaboralDaoImpl'
	 * 
	 * @param userConn
	 */
	public RcPsicoSituacionLaboralDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "IDEA.RC_PSICO_SITUACION_LABORAL";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected RcPsicoSituacionLaboral fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			RcPsicoSituacionLaboral dto = new RcPsicoSituacionLaboral();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected RcPsicoSituacionLaboral[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			RcPsicoSituacionLaboral dto = new RcPsicoSituacionLaboral();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		RcPsicoSituacionLaboral ret[] = new RcPsicoSituacionLaboral[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(RcPsicoSituacionLaboral dto, ResultSet rs) throws SQLException
	{
		dto.setIdSituacionLaboral( rs.getLong( COLUMN_ID_SITUACION_LABORAL ) );
		dto.setSituacion( rs.getString( COLUMN_SITUACION ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(RcPsicoSituacionLaboral dto)
	{
		dto.setIdSituacionLaboralModified( false );
		dto.setSituacionModified( false );
	}

	/** 
	 * Returns all rows from the RC_PSICO_SITUACION_LABORAL table that match the specified arbitrary SQL statement
	 */
	public RcPsicoSituacionLaboral[] findByDynamicSelect(String sql, Object[] sqlParams) throws RcPsicoSituacionLaboralDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new RcPsicoSituacionLaboralDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the RC_PSICO_SITUACION_LABORAL table that match the specified arbitrary SQL statement
	 */
	public RcPsicoSituacionLaboral[] findByDynamicWhere(String sql, Object[] sqlParams) throws RcPsicoSituacionLaboralDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			throw new RcPsicoSituacionLaboralDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
	}
	
	/**
	 * Method 'getTableNameInnerJoin'
	 * 
	 * @return String
	 */
	public String getTableNameInnerJoin()
	{
		return "IDEA.RC_PSICOLOGIA";
	}
	
	/**
	 * Metodo que obtiene el objeto RcRehaNivelEducativo a traves del idRehabilitador
	 * 
	 * @param sql
	 * @param sqlParams
	 * @return
	 * @throws RcRehaProbSensorialesDaoException
	 */
	public RcPsicoSituacionLaboral findByInnerJoinRCRehabilitador( long idPsicologia ) throws RcPsicoSituacionLaboralDaoException{
		
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT_INNER_JOIN 
					           + " INNER JOIN " + getTableNameInnerJoin()
					           + " ON " + getTableNameInnerJoin() + ".ID_SITUACION_LABORAL = " + getTableName() + ".ID_SITUACION_LABORAL"
					           + " WHERE " + getTableNameInnerJoin() + ".ID_RC_PSICOLOGIA =" + idPsicologia;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchSingleResult(rs);
		}
		catch (Exception _e) {
			throw new RcPsicoSituacionLaboralDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		}
	}

}
