/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.sorin.idea.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the plantillas table.
 */
public class PlantillasPk implements Serializable
{
	protected int idPlantilla;

	/** 
	 * This attribute represents whether the primitive attribute idPlantilla is null.
	 */
	protected boolean idPlantillaNull;

	/** 
	 * Sets the value of idPlantilla
	 */
	public void setIdPlantilla(int idPlantilla)
	{
		this.idPlantilla = idPlantilla;
	}

	/** 
	 * Gets the value of idPlantilla
	 */
	public int getIdPlantilla()
	{
		return idPlantilla;
	}

	/**
	 * Method 'PlantillasPk'
	 * 
	 */
	public PlantillasPk()
	{
	}

	/**
	 * Method 'PlantillasPk'
	 * 
	 * @param idPlantilla
	 */
	public PlantillasPk(final int idPlantilla)
	{
		this.idPlantilla = idPlantilla;
	}

	/** 
	 * Sets the value of idPlantillaNull
	 */
	public void setIdPlantillaNull(boolean idPlantillaNull)
	{
		this.idPlantillaNull = idPlantillaNull;
	}

	/** 
	 * Gets the value of idPlantillaNull
	 */
	public boolean isIdPlantillaNull()
	{
		return idPlantillaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PlantillasPk)) {
			return false;
		}
		
		final PlantillasPk _cast = (PlantillasPk) _other;
		if (idPlantilla != _cast.idPlantilla) {
			return false;
		}
		
		if (idPlantillaNull != _cast.idPlantillaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idPlantilla;
		_hashCode = 29 * _hashCode + (idPlantillaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.sorin.idea.dto.PlantillasPk: " );
		ret.append( "idPlantilla=" + idPlantilla );
		return ret.toString();
	}

}
